### ISSUE TITLE
[CMake] CLI11_BUILD_DOCS=ON does not generate the documentation with Doxygen

### ISSUE THREAD

**Issue by Spixmaster** [henryiii/CLI11#1019]

**Comment by henryiii** [comment]
https://github.com/CLIUtils/CLI11/blob/3afddf3578ccc157e78f4edaf30635ebb3e3991b/CMakeLists.txt#L226-L228

Looks like that enables the docs unconditionally when that is set?

**Comment by henryiii** [comment]
You do need to build the `docs` target, that's only the configure setup, IIRC. It's just enabling the standard CMake doxygen support.

**Comment by Spixmaster** [comment]
I just tested it again. It works now with v2.4.2. `doxygen` generates the documentation.

I do not know whether version v2.4.2 fixed it which was released in the meantime. At the time of submitting the issue, I used v2.4.1.
