### ISSUE TITLE
Question: Option requires one of two other options

### ISSUE THREAD

**Issue by ptc-tgamper** [henryiii/CLI11#1034]
Hi,

I am in the situation where I have options `-D`, `-E`, and `-F`. What I need is that if `-D` is provided, then exactly one of `-E` and `-F` has to be specified, too.
Providing `-D` with `-E` is valid. Providing `-D` with `-F` is valid.
Providing only `-D` is invalid. Providing `-D`, `-E`, and `-F` is invalid. Providing only `-E` is invalid. Providing only `-F` is invalid.

I haven't found a way to do this yet.

Otherwise I am really happy with CLI11 and the functionality it provides. Kudos to the authors.

Thanks,
Thomas

**Comment by phlptp** [comment]
I think the easiest way would be to put the D option in 1 option group and the E and F option in another group.  Make the E and F options exclusive or use the option_group required count so the min and max required is 1.   Then for the D group use it to trigger the E and F option group on.   using `CLI::TriggerOn` helper.      To make the help more useful you may have to catch some specific errors related to using the E and F without D to make the help message more useful

**Comment by ptc-tgamper** [comment]
I had to do both. Mark E and F to exclude each other, and to tell their group that only a single option is allowed. Then I am getting reasonable error messages.

Still this leaves me a bit unhappy, because I have now groups in the help message, where I would prefer not to have them. Especially because I have options that belong together, but are in different groups.

**Comment by phlptp** [comment]
in the main branch, if you add an option group with a name that begins with a '+'  it should now display as part of the parent group/app.
