### ISSUE TITLE
New error after updating to 2.4.2: add_option throws error when adding option "--h"

### ISSUE THREAD

**Issue by DSMitten** [henryiii/CLI11#1048]
Existing built-in options include `-h` and `--help`

I have code which adds the following:
```cpp
parser->add_option("--h", myArgs.headerPath, "Path to header file");
```

The intent is that you would call `myprogram.exe <other-options> --h <path-to-header>`

This worked in 2.4.0, but breaks in 2.4.2.  After updating to the latest vcpkg port, I get the following error:
`error: added option matched existing option name: h is already added`

I would not expect the parser to treat `-h` and `--h` the same, since they are different switches.
After commenting out my line, when running `myprogram.exe --h`, it invokes help, so it looks like the parser isn't distinguishing between single and double dashes at all.

Testing this out with other letters, if I try `add_option` for both `-t` and `--t`, it errors out, also saying that it is a duplicate argument name, but when parsing it doesn't treat them as the same.

**Comment by phlptp** [comment]
One reason for not allowing that is that when parsing config files they would conflict.   We could possibly allow it if the option was not able to present in a config file which is the case for the help option.   This was changed in a recent release to fix the ambiguity in config file writing and reading,  naming positional the same as a short or long option will also cause an error.

**Comment by henryiii** [comment]
I’m not sure it makes sense to put short options in a config file.

**Comment by phlptp** [comment]
If an option only has a short option defined, it still needs to be able to be defined in a config file.   If it defines both, the long option name is used for generation.  Also it would be rather confusing if a short option name used in a config file didn't match up with the option that defined the short name.

**Comment by DSMitten** [comment]
This worked in 2.4.0. There are no notes in 2.4.2 indicating that it includes a breaking change to prevent the use of single and double-dash options with the same name. Was this an intentional breaking change?

**Comment by DSMitten** [comment]
From a library consumer's standpoint, it was confusing to treat `-t` and `--t` as the same when validating the parser but not when actually parsing.

If you want to avoid conflicts, it might make sense to just ban the use of two-dash single-letter arguments. At least then the errors will be consistent and make sense.  If I print out a usage statement and it shows that there is a `-t` option but no `--t` option, it won't make sense that I can't add the `--t` option.

It would just be nice for the old behavior to still work.

**Comment by phlptp** [comment]
The old behavior was an untested edge, so wasn't considered a breaking change.    It also was the source of an error in configuration file processing that needed to be resolved.    Banning two dash single character options would be a breaking change, so I don't think just banning them is a viable option.     I think the help, --h conflict can be resolved easily, but not sure what the most appropriate general solution to the confusion would be.   Potentially more helpful errors.

**Comment by henryiii** [comment]
Would fixing just the "h" case solve your specific case?

I don't know if config file processing concerns should break valid usages that are not using config files.

How about if a short option without a long option is considered for a conflict, like `-t` and `--t` was banned, but `-t, --other` and `--t` wasn't, since config files could use "other" for the first option? That is, config files always use or prefer the long option, and the check respects that?

**Comment by DSMitten** [comment]
On the one hand, on the command line, I do think that `-` and `--` should always be treated differently. I'm not sure how config files that cli11 parses are formatted; I've never used that capability.

But, your proposal is reasonable and would unblock my scenario. You combine `-h, --help` so I would be allowed to use `--h` in that case.

EDIT: In the event of attempting to add `-t` and `--t` options, where `-t` doesn't have an associated long option, it would be good if the error message is clear that `-t` conflicts with `--t` but `-t` tied to a long option would not. I'm not sure the best way to communicate that.

**Comment by phlptp** [comment]
In the main branch, this should be resolved.    And options won't conflict as long as the previous one is not configurable.
