### ISSUE TITLE
Access violation crash when add subcommand in seperate function

### ISSUE THREAD

**Issue by TeCHiScy** [henryiii/CLI11#1050]
This code crashes with `EXC_BAD_ACCESS` on my Macbook M1 Pro, 14.5 (23F79).
Run command is `./test patch -f a -h`.
Compile command is `g++ main.cpp -std=c++20 -O2 -o test -I./include`.

```c++
#include "CLI11.hpp"

int patch(CLI::App* app) {
  std::string f, p;
  auto cmd = app->add_subcommand();
  cmd->add_option("-f", f)->option_text("filename");
  cmd->add_option("-p", p)->option_text("filename");
  cmd->callback([&app, &f, &p]() { std::cout << "ok"; });
  return 0;
}

int main(int argc, char* argv[]) {
  CLI::App app{};
  argv = app.ensure_utf8(argv);
  patch(&app);
  CLI11_PARSE(app, argc, argv);
  return 0;
}
```

However, if you add subcommand directly inside main, it won't crash.
```c++
#include "CLI11.hpp"

int main(int argc, char* argv[]) {
  CLI::App app{};
  argv = app.ensure_utf8(argv);

  std::string f, p;
  auto cmd = app->add_subcommand();
  cmd->add_option("-f", f)->option_text("filename");
  cmd->add_option("-p", p)->option_text("filename");
  cmd->callback([&app, &f, &p]() { std::cout << "ok"; });

  CLI11_PARSE(app, argc, argv);
  return 0;
}
```

It would be clear to put sub command logic in seperate functions. Is there any limitations on usage like this? Or is this a bug?

**Comment by henryiii** [comment]
`f` and `p` are destroyed when you leave the function's frame. Try making them shared pointers, for example.

**Comment by TeCHiScy** [comment]
> `f` and `p` are destroyed when you leave the function's frame. Try making them shared pointers, for example.

Thanks! I addressed this problem. And this [example](https://github.com/CLIUtils/CLI11/blob/4ecbdd83e51eb49d1e4e99bea7c55e36c0426d34/examples/subcom_in_files/subcommand_a.cpp) helps a lot.
