### ISSUE TITLE
How to get the last argument without option? (like the basic "ls" command)

### ISSUE THREAD

**Issue by alexisfrjp** [henryiii/CLI11#1057]
I'm surprised there is no simple argument in any of the basic example.

I'd like to parse:
* `./myapp anarg`
* `./myapp -f myfile anarg`
* potentially `./myapp anarg -f myfile`

I've used 
```
std::string path;
CLI::Option *opt_path = cli_params.add_option("-f,--file", path, "File to use")->check(CLI::ExistingFile);
```

but there is nothing to catch the `anarg` that doesn't belong to any option and isn't an flag (no `-` or `--`).

How can I do that?

**Comment by phlptp** [comment]
This type of argument is called a positional argument.   You can capture it through a call like
```c++
std::string arg
CLI::Option *opt_path = cli_params.add_option("positional", arg, "an argument");
```

Key indicator is argument with no `-` in front of the name string

**Comment by alexisfrjp** [comment]
Thank you!
