### ISSUE TITLE
Print argv from a callback

### ISSUE THREAD

**Issue by eolivi-fy** [henryiii/CLI11#1063]
Hi
first of all, thank you for this good library!

I'd like to be able to print the command run:
```
> ./MyBinary --input file.txt --num 4 --log debug
Command run was: "./MyBinary --input file.txt --num 4 --log debug"
...
```

Of course I could simply call:
```
for (int i = 0; i < argc; i++)
   std::cout << argv[i] << " ";

// just before
app.parse(argc, argv);
```

But I feel there could be a way using a callback ?

This does it almost:
```
app.parse_complete_callback([&app](){
   std::cout << "Command run:\n" << app.config_to_str()) << std::endl;
}
```
> Command run:
log="debug"
input="file.txt"
num=4

maybe there is another way ?

**Comment by phlptp** [comment]
I don't think a way was built to regenerate the command line directly inside CLI11.

**Comment by eolivi-fy** [comment]
Thanks, good enough then with `app.config_to_str()`

Feel free to close
