### ISSUE TITLE
Not Compatible on VS2015 XP support (v140_xp) - can not find <processthreadsapi.h>

### ISSUE THREAD

**Issue by yuvalkuck** [henryiii/CLI11#1071]
can not find #include <processthreadsapi.h> with error: 
cli\impl/Argv_inl.hpp(52): fatal error C1083: Cannot open include file: 'processthreadsapi.h': No such file or directory
happen in 2.4.1 & 2.4.2 

a similar problem is described here:
https://stackoverflow.com/questions/54736057/how-to-fix-errors-on-standard-headers-in-visualstudio-2017-on-windows-10-build

I use VS2015 described as the lower limit of CLI11. 
On Windows 10 plus CMake with generate_toolset = v140_xp

If I replace the include to windows.h I get diffrent error ... 
>...\cli\impl/StringTools_inl.hpp(12): warning C4464: relative include path contains '..'
>...\impl/StringTools_inl.hpp(348): error C2131: expression did not evaluate to a constant
>  ...\cli\impl/StringTools_inl.hpp(348): note: failure was caused by non-constant arguments or reference to a non-constant symbol
>  ...\cli\impl/StringTools_inl.hpp(348): note: see usage of 'npos'
>...\cli\impl/StringTools_inl.hpp(348): error C2051: case expression not constant

I miss something ? 
maybe the VS2019, which is also installed on that system, did something that misled the build process? 

any fast solution?

**Comment by phlptp** [comment]
You could probably go back a few versions of CLI11 to before we added the wide character support.  My guess is that is where the issue with VS2015 was introduced.  There are no CI systems that support 2015 any more, and I don't use it.   So it will be hard to debug for us.

**Comment by yuvalkuck** [comment]
OK, tested with 2.3.2, looks OK, thanks for fast answer
