### ISSUE TITLE
cmake version deprecation warning

### ISSUE THREAD

**Issue by oschonrock** [henryiii/CLI11#1082]
I am using cmake 3.30

and just started getting this:

```
CMake Deprecation Warning at ext/CLI11/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

**Comment by phlptp** [comment]
what platform are you running on, I do not get that warning with CMake 3.30.

**Comment by henryiii** [comment]
That warning was added in CMake 3.31.

**Comment by henryiii** [comment]
I'd be okay to make this require 3.10+ and drop the old workaround for an old MSVC built-in CMake.

**Comment by oschonrock** [comment]
> That warning was added in CMake 3.31.

yes apologies.. 3.31 

It's the version you now get on ubuntu 24.04, when you do

sudo snap install cmake 

(the snap version being newer than what you get from the apt repos) 

I run it, because latest cmake is usually worth having.

**Comment by oschonrock** [comment]
> I'd be okay to make this require 3.10+ and drop the old workaround for an old MSVC built-in CMake.

That would be great, I currently have it locally modified like so:

```patch
$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b35b268..8eff25a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,4 +1,4 @@
-cmake_minimum_required(VERSION 3.5)
+cmake_minimum_required(VERSION 3.10)
 # Note: this is a header only library. If you have an older CMake than 3.5,
 # just add the CLI11/include directory and that's all you need to do.
```
And that "works for me".. 

of course can comment better on the wider impact.

**Comment by oschonrock** [comment]
> what platform are you running on, I do not get that warning with CMake 3.30.

apologies cmake *3.31* .

I am running ubuntu 24.04 with

sudo snap install cmake
(to get the latest cmake)

**Comment by phlptp** [comment]
Ok, I will probably be testing 3.31 on some of my applications the week of the 18th.   Unless someone makes the changes before then I will update the minimum cmake version at that time.
