### ISSUE TITLE
Question: Does the --no-flag syntax affect "needs" and "excludes"?

### ISSUE THREAD

**Issue by ghost** [henryiii/CLI11#1083]
Hello. I've noticed that the following does not work:

```
    bool flag_a = true;
    bool flag_b = true;
    app->add_flag("--flag-a,!--no-flag-a", flag_a, "enable a")->default_val(true);
    app->add_flag("--flag-b,!--no-flag-b", flag_b, "enable b")->default_val(true)->needs("--flag-a");
```
Running the following does not produce any error messages. Is it expected?

> ./myapp --no-flag-a --flag-b

When I remove the  "!--no-flag-a" part and set flag_a to false an error is shown if I run my program without explicitly providing --flag-a.

> ./myapp --flag-b

**Comment by phlptp** [comment]
After staring at this for a bit I think it is operating as expected.
The needs defines that the other option needs to be specified which it is,  acting the same as 
```
./myapp flag-a=false --flab-b
```

if you only want flag_b to be allowed if flag a is true you will need something a little different 
```C++
bool flag_a = true;
    bool flag_b = true;
    auto *optA=app->add_flag("--flag-a", flag_a, "enable a")->disable_flag_override()->default_val(true);
    app->add_flag("!--no-flag-a", flag_a, "disable a")->disable_flag_override()->excludes(optA);
    app->add_flag("--flag-b,!--no-flag-b", flag_b, "enable b")->default_val(true)->needs(optA);
```

**Comment by ghost** [comment]
> if you only want flag_b to be allowed if flag a is true you will need something a little different

Thank you for clarifying this. By the way, it seems that force_callback is unnecessary in your code snippet. It prevents the program from running even if only --no-flag-a is provided. (It says--no-flag-a excludes --flag-a)

**Comment by phlptp** [comment]
> > if you only want flag_b to be allowed if flag a is true you will need something a little different
> 
> Thank you for clarifying this. By the way, it seems that force_callback is unnecessary in your code snippet. It prevents the program from running even if only --no-flag-a is provided. (It says--no-flag-a excludes --flag-a)

removed,
