### ISSUE TITLE
Changing the underlying type of an enum class options results in an unintuitive error message

### ISSUE THREAD

**Issue by to-mas-kral** [henryiii/CLI11#1086]
I'm using CLI11 version 2.3.2 from vcpkg.

```cpp
enum class FooType : std::uint8_t {
    A,
    B,
};

int
main(int argc, char **argv) {
    CLI::App foo_app("Foo");

    auto type = FooType::A;

    const std::map<std::string, FooType> foo_map{
        {"a", FooType::A},
        {"b", FooType::B},
    };

    foo_app.add_option("-f,--foo", type, "FooType")
        ->transform(CLI::CheckedTransformer(foo_map, CLI::ignore_case))
        ->default_val(FooType::A);
}
```

This code results in an exception:
```
terminate called after throwing an instance of 'CLI::ValidationError' what():  --foo: Check 
```

Changing the underlying type of `FooType` to `std::uint32_t` fixes the issue.

**Comment by phlptp** [comment]
Hmmm that is an interesting case.   I think the reason is that "a" and "b" as as single character are valid for the type of the enum.   Not sure of the chain without digging deeper, I will take a look see if something can be done or the error cleared up.

**Comment by phlptp** [comment]
Fixed
