### ISSUE TITLE
Option::expected(min, max) does not respect the range

### ISSUE THREAD

**Issue by gon1332** [henryiii/CLI11#1090]
Consider the following program with CLI11 2.4.2:

```c++
#include <CLI/CLI.hpp>

int main(int argc, char *argv[])
{
    CLI::App cli("x");
    cli.add_option("args")
        //->allow_extra_args()
        ->required()
        ->expected(2, 4);

    CLI11_PARSE(cli, argc, argv);
}
```

The below table summarizes the results of the above code with a set of inputs, without and with `allow_extra_args()`. Empty cells mean no output (which is success in our case):

| input     | only expected(2, 4) | with allow_extra_args() |
|-----------|---------------------|-------------------------|
| a         | args: At least 2 required but received 1                    | args: At least 2 required but received 1                        |
| a b       |                     |                         |
| a b c     | The following argument was not expected: c                    |                         |
| a b c d   | The following argument was not expected: d c                    |                         |
| a b c d e | The following argument was not expected: e d c                    | args: At Most 4 required but received 5                        |

What I would expect by using just `expected(2, 4)` is achieved only if it's accompanied by a `allow_extra_args()`.

Is this expected for `expected(min, max)`?

**Comment by phlptp** [comment]
I will look into this more.
