### ISSUE TITLE
Function add_flag with default_val won't work

### ISSUE THREAD

**Issue by Work-Developer-Sina** [henryiii/CLI11#1091]
I'm trying to use  add_flag  and if the flag isn't provided set a default value.
The parameter is a boolean variable and flag name is something like this "--flag, !--not-flag"
```
cli_option =  cli_app_->add_flag(flag_name, parameter, flag_description);
cli_option->default_val(true);
```                     
This worked with old versions. I updated CLI11 and I get no compile error but default_val won't apply to the variable if nothing is provided then it would false.

**Comment by phlptp** [comment]
If that worked before it was a bug.   
use 
```c++
cli_option =  cli_app_->add_flag(flag_name, parameter, flag_description);
cli_option->default_val(true)->force_callback();
```

This will force the value to be set after every run even it the flag was not used.   

default_val is the value used if nothing is provided and a value is needed.  This can be through force_callback or through retrieving the option value directly.

**Comment by phlptp** [comment]
going to close this one, as I think it is resolved and haven't heard anything in a while
