### ISSUE TITLE
Default option value across subcommand invocations

### ISSUE THREAD

**Issue by mdriu** [henryiii/CLI11#1092]
I'm currently using CLI11 to fill a vector of structs via command line.

After spending quite a lot of time on the documentation, I've ended up implementing this by:
- having a subcommand with options that match the struct fields
- tiding the subcommand options to the fields of a temporary struct
- adding a subcommand parse complete callback, where I push the temporary struct into a vector, and then "reset" the subcommand app by means of the `clear()` method

Minimal working example below:

```cpp
// mwe.cpp
#include "CLI/CLI.hpp"
#include <vector>
#include <iostream>

struct Cat { int age; int weight; };

int main(int argc, char *argv[])
{
    CLI::App app;
    Cat tmp;
    std::vector<Cat> v;

    CLI::App *pCatApp = app.add_subcommand("cat", "Populate cat struct");
    pCatApp->add_option("--age", tmp.age, "Cat age")->default_val(-1);
    pCatApp->add_option("--weight", tmp.weight, "Cat weight")->default_val(-1);
    pCatApp->parse_complete_callback([&pCatApp, &tmp, &v](){
        v.push_back(tmp);
        pCatApp->clear();
    });
    CLI11_PARSE(app, argc, argv);

    for (size_t idx = 0; idx < v.size(); idx++)
    {
        std::cout << "[" << idx << "] cat.age=" << v[idx].age << " cat.weight=" << v[idx].weight << std::endl;
    }
    return 0;
}
```

This _kind of works_ but of course option defaults are not retained.
This means that as soon as I specify one option, the actual default value gets lost and the last given is used instead.
With the example above, you get:

```shell
$ ./mwe cat --age 3 --weight 4 cat --age 5
[0] cat.age=3 cat.weight=4
[1] cat.age=5 cat.weight=4
```

when one would really like:

```shell
$ ./mwe cat --age 3 --weight 4 cat --age 5
[0] cat.age=3 cat.weight=4
[1] cat.age=5 cat.weight=-1
```

I feel like I'm a bit abusing the subcommand and parse complete concepts here, hence my main question is whether I have missed any better way to implement this. If instead that's the only way, how would you suggest to retain the default value across subcommands invocations?

**Comment by phlptp** [comment]
Things like this are one of the designed use cases for parse_complete_callback on subcommands, so I don't feel like that is an abuse at all.   
```c++
#include "CLI/CLI.hpp"
#include <vector>
#include <iostream>

struct Cat { int age; int weight; };

int main(int argc, char *argv[])
{
    CLI::App app;
    Cat tmp;
    std::vector<Cat> v;

    CLI::App *pCatApp = app.add_subcommand("cat", "Populate cat struct");
    pCatApp->add_option("--age", tmp.age, "Cat age")->default_val(-1)->force_callback();
    pCatApp->add_option("--weight", tmp.weight, "Cat weight")->default_val(-1)->force_callback();
    pCatApp->parse_complete_callback([&tmp, &v](){
        v.push_back(tmp);
    })->immediate_callback();
    CLI11_PARSE(app, argc, argv);

    for (size_t idx = 0; idx < v.size(); idx++)
    {
        std::cout << "[" << idx << "] cat.age=" << v[idx].age << " cat.weight=" << v[idx].weight << std::endl;
    }
    return 0;
}
```

two tweaks I would make.  add `force_callback` to the options, this will set the value on each call using the stored default if no option was given.   Second the `immediate_callback` on the subcommand  this lets CLI know to do a full reset of the subcommand at the start of each call so you don't have to do the clear yourself.

**Comment by mdriu** [comment]
Thank you @phlptp, that worked like a charm :)

As a user, whilst going through the documentation and quickly inspecting the source code, I didn't grasp that `immediate_callback` resulted in a subcommand reset. Can you please elaborate a bit on why `immediate_callback` does that, and on whether that is a side effect or a deliberate choice?

**Comment by phlptp** [comment]
The intention behind `immediate_callback` is to allow a subcommand to be called multiple times independently.  So the reset is very purposely part of that.   It also manipulates some of the callbacks, but in your case you were doing that already through the `parse_complete_callback`.     So that part had little impact on your code.     Basically the difference is that with `immediate_callback` there are multiple independent runs of the subcommand vs multiple runs that build on eachother.

**Comment by mdriu** [comment]
Very clear thank you! I think I can close this
