### ISSUE TITLE
Feature request: golang style options

### ISSUE THREAD

**Issue by robiwano** [henryiii/CLI11#1107]
I'm refactoring a golang utility in C++, and the command line options in golang are all starting with a single dash:
`-multi-char-option` 
Which CLI11 chokes on, as it assumes it is a single char option.

**Comment by phlptp** [comment]
In the main branch, there is a new modifier `.allow_non_standard_option_names()`   this will allow single dash  long form options.

**Comment by robiwano** [comment]
Yes! Awesome!

**Comment by henryiii** [comment]
Should we think about making a new release soon?

**Comment by phlptp** [comment]
Yeah I was starting to wonder that too.  There have been a number of fixes, improvements and changes that might be good to get in a release.
