### ISSUE TITLE
how to check whether an argument exist on the command line or not?

### ISSUE THREAD

**Issue by liwei46** [henryiii/CLI11#651]
Hi,

This is a great project. 
Here is a trivial question. As in the title, 
how to check whether an argument exist on the command line or not?
Which function to use?  Thanks.
regards,

**Comment by henryiii** [comment]
`->count()` on the option itself (or treat it as a bool), or you can use `app.count(name)`, where name is the name of the option. Though I'd look at the various examples, and see how those are structured.
