### ISSUE TITLE
Check  () for string length ? 

### ISSUE THREAD

**Issue by SadE54** [henryiii/CLI11#655]
Hi , 

I'm discovering this nice lib, but I'm a little lost with all the possibilities . Is there an easy way to check if a provided string as a option has a min length  ? 

Regards,

**Comment by henryiii** [comment]
```cpp
option->check(
    [](const std::string &str) {
        return str.length() > 1 ? "" : "String too short";
    }
);
```

You can also subclass Validator instead if you want all the fancy unions and things with other checks.

**Comment by henryiii** [comment]
Resolved?
