### ISSUE TITLE
Cannot compile with /GR- (RTTI disabled) and _HAS_STATIC_RTTI=0 with MSVC compiler

### ISSUE THREAD

**Issue by inkychris** [henryiii/CLI11#669]
I get the following error compiling a CLI11 example with `/GR-` (RTTI disabled) and also with `-D_HAS_STATIC_RTTI=0`:

```
CLI11.hpp(6763,25): error C2280: 'std::shared_ptr<CLI::ConfigBase> std::dynamic_pointer_cast<CLI::ConfigBase,CLI::Config>(const std::shared_ptr<CLI::Config> &) noexcept': attempting to reference a deleted function
```

The condition check for whether to use a dynamic or static cast is the issue here:
https://github.com/CLIUtils/CLI11/blob/815553211b644b2a64b5dc671c602233c49c065f/include/CLI/App.hpp#L1546-L1550

MSVC does not appear to modify the value of [`__cpp_rtti`](https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations#__cpp_rtti) which remains `1`, but rather sets [`_CPPRTTI`](https://docs.microsoft.com/en-us/cpp/build/reference/gr-enable-run-time-type-information) instead. Visual Studio's intellisense doesn't seem to correctly interpret this value but it does in fact change depending on `/GR[-]`.

If my understanding is correct, the condition for `_HAS_STATIC_RTTI` should also be checking for a value of `1`, not `0`.

**Comment by phlptp** [comment]
I think the `_HAS_STATIC_RTTI` is correct.  If that is set you want to use the static cast,  it looks like we need to expand the conditions of `__cpp_rtti` and possibly a similar one for `_CPPRTTI`   

We also might want to flip the conditions a little to better reflect the different possibilities you described.   Need to think a little more

**Comment by phlptp** [comment]
I added a potential fix in #666,  not sure if you can check that, or if we should try to tweak one of the CI builds with  RTTI disabled like in the issue?  @henryiii thoughts?

**Comment by inkychris** [comment]
I was under the impression that `_HAS_STATIC_RTTI=0` defined but disabled it, although I think this STL source suggests I misunderstood this variable, it seems a little backwards to me!

https://github.com/microsoft/STL/blob/178b8406a5647507e759442960f17cd33045cdf5/stl/inc/yvals_core.h#L591-L597

Your changes seem to have fixed the issue for me and it's correctly selecting the static cast now.

**Comment by phlptp** [comment]
I think I have always interpreted it as if that is set it has RTTI but don't use the dynamic RTTI.

**Comment by inkychris** [comment]
~~Yeah that STL snippet I linked seems to agree with you, since it throws an error if you both define `_HAS_STATIC_RTTI` and have `/GR` (enable RTTI). I think I need to pull those definitions out of my codebase!~~

Actually on reflection, I think the value of that definition is taken into consideration, as implied by both these threads:
- https://www.mail-archive.com/cfe-commits@lists.llvm.org/msg235273.html
- https://github.com/microsoft/STL/issues/340

That said, your proposed change is still behaving correctly. CLI11 should be using the static cast if `_HAS_STATIC_RTTI=0`. The original condition was in fact supposed to be checking for a value of 1 and not 0.
