### ISSUE TITLE
Options: Require one of two

### ISSUE THREAD

**Issue by Tectu** [henryiii/CLI11#672]
I might be missing something very obvious here - I'm looking for a way to give a (sub)command two options `--id` and `--file`. I need to enforce that either one of them (but not both - mutually exclusive) is required.

How can I do that?

**Comment by phlptp** [comment]
you can put both options in an option_group and use `require_option(1)`     This will enforce that one and only one option from that group or subcommand is needed.

**Comment by Tectu** [comment]
Exactly what I was looking for. Works like a treat - thanks!

It's a nice library to work with compared to other solutions that were evaluated - keep up the good work :)
