### ISSUE TITLE
Support for custom namespace for single header file generation

### ISSUE THREAD

**Issue by jstrzebonski** [henryiii/CLI11#680]
We're using CLI11 (single header) in a library https://github.com/DARMA-tasking/vt, which can be next linked to an app, that itself uses CLI11 for its own purposes. If there's a mismatch in versions it can lead to segmentation fault. It seems that CLI11 can be the cause of ODR violations. The fix is super easy, just use a different namespace for CLI included in our library.

In version 1.9.0, `MakeSingleHeader.py`, when passed --namespace argument, would simply surround whole code with that namespace. In current version the script replaces `{namespace}` in CLI11.hpp.in file with a given namespace, but inside that namespace, there are still references to 'original' `CLI11` namespace which causes compilation error.

I think that something as simple as:

```python
    new_namespace = namespace + "::"
    single_header = re.sub(r'\bCLI::\b', new_namespace, single_header)
```

added to `make_header()` should resolved the problem.

**Comment by henryiii** [comment]
Oops, forgot to fix this. Feel free to make a PR, much more likely to not forget that!
