### ISSUE TITLE
Allow to set a config root folder with set_config

### ISSUE THREAD

**Issue by Firefly35** [henryiii/CLI11#682]
Sometimes an application will host several configurations (profiles) in its configuration folder (for instance in .app/profiles/...).
However, set_config doesn't provide a way to add a root_config folder where a profile would be searched for if it isn't found from its filename.

**Comment by phlptp** [comment]
What do you think of the solution in #698?

**Comment by Firefly35** [comment]
It's beyond my expectations, moreover it allows to specify several paths to
look for. It is a great solution to the issue I set.
Thanks for this proposition.


Le lun. 31 janv. 2022 à 23:45, Philip Top ***@***.***> a
écrit :
