### ISSUE TITLE
Enhancement: allow an option or a command option set to be ignored in config file

### ISSUE THREAD

**Issue by Firefly35** [henryiii/CLI11#685]
Sometimes, there are some options that must not be persistent between the tool calls. Or a whole subcommand option set.

Hence, adding all options to the configuration file when using App::config_to_str(true,true) adds all the options of all commands and subcommands to the configuration file.

It would be a useful enhancement to have an option/command modifier to describe that the option/command must not be exported to the configuration file when using App::config_to_str(true,true).

For instance :
at the command level:
CLI::App * command = ...;
command->configExport(bool);

at the option level:
command->add_option(...)->configExport(bool);

**Comment by phlptp** [comment]
The `configurable(false)` option already disables the option from being used or written to a config file.  That works on option groups and subcommands as well.  Is this different than what you are proposing?

**Comment by Firefly35** [comment]
No it's exactly the option I wanted, sorry I didn't figure out it was the
way to go.
Thanks a lot for your answer.

Le lun. 13 déc. 2021 à 18:06, Philip Top ***@***.***> a
écrit :
