### ISSUE TITLE
Can't use custom Validator to transform string

### ISSUE THREAD

**Issue by JonathanGzzBen** [henryiii/CLI11#687]
I want to use `CLI::Validator` to transform a string into another. I am making a validator object and passing it to the `check` method of and option object. Simplified, even this code shows an error in terminal.

```cpp
auto transform_datetime = CLI::Validator(
    [](std::string &input) {
      return std::string("new string");
    },
    "DATETIME", "Datetime transformer");
```

I am adding this validator to a subcommand.

```cpp
CLI::App cli_global{"weighterm 0.2"};
auto &modify_command = *cli_global.add_subcommand(
    "modify", "Modify specific weight measurement");
```

And this is how I add validator to the subcommand:

```cpp
std::string datetime_str{};
modify_command
    .add_option("datetime", datetime_str, "Datetime of weight measurement")
    ->check(transform_datetime);
```
If run with `weighterm modify yesterday`, where `weighterm` is the name of the binary,  I get this error:

```
datetime: new string
Run with --help for more information.
```

Edit: I am using version 2.1.1

**Comment by phlptp** [comment]
I think we need to update the validator documentation.  

So, the return of a validator is an error string.  If that string is not empty an error was generated and the parsing will fail.  

Second issue is that the check() does not allow modification.  
What you want is the transform() call  so the code you need is
```C++
auto transform_datetime = CLI::Validator(
    [](std::string &input) {
      input="new string";
      return "";
    },
    "DATETIME", "Datetime transformer");
```

```
std::string datetime_str{};
modify_command
    .add_option("datetime", datetime_str, "Datetime of weight measurement")
    ->transform(transform_datetime);
```

transform can act as a check as well if the return is not empty.

**Comment by JonathanGzzBen** [comment]
Thank you, it works now. I may update the documentation with that information this week.
