### ISSUE TITLE
Symlink tests/mesonTest/subprojects/CLI11 causes directory cycle

### ISSUE THREAD

**Issue by boris-kolpackov** [henryiii/CLI11#696]
The `tests/mesonTest/subprojects/CLI11` symlink points to its parent directory (`../../..` to be precise) which causes a directory cycle that in turn can cause traversal issues for various tools. In case of `build2` you get a warning, which is annoying:

```
warning: directory cycle caused by symlink build/.bpkg/tmp/78c1e67e6423/upstream/tests/mesonTest/subprojects/CLI11/
  info: symlink target build/.bpkg/tmp/78c1e67e6423/upstream/
```

Also note that directory symlinks on Windows are tricky (if at all available): https://build2.org/article/symlinks.xhtml#windows

**Comment by jspelletier** [comment]
Hello,
This symlink is causing job failures in gitlab when this repo is used as submodules and the git strategy is clone. It seems this can also happen in fetch strategy if runner was previously in clone mode.

I don't know why you need this file but couldn't you instead create it at runtime when running tests? Please consider removing this symlink!

The symlink causes errors such as the following:
Remove-Item : There is a mismatch between the tag specified in the request and the tag present in the reparse point
```
At C:\Users\xxxxxxx\AppData\Local\Temp\build_script368801463\script.ps1:224 char:3
+   Remove-Item -Force -Recurse "C:\gitlab-runner\builds\CsRJCNVP\0\yyyy...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand
```
 gitlab is unable to delete the submodule folder and this causes errors later on when trying to execute git clone operations
 
 Thanks
