### ISSUE TITLE
Add Lyra to list of known alternatives

### ISSUE THREAD

**Issue by jstaursky** [henryiii/CLI11#699]
Would it be possible to add an overload of the `|` operator to add multiple options? Something similar to what is done in the [Lyra](https://github.com/bfgroup/Lyra) cmdline library. It provides a nice listing of all the options.

**Comment by phlptp** [comment]
I am not sure that would work very well in CLI11.  the `add_option` method returns an option pointer so you can customize the option behavior quite a bit.    From what I can tell Lyra returns original caller and doesn't allow much in the way of customization.  

That being said I am sure it technically could be done,  but also not sure it would a good idea for CLI11 to support that as it would have a lot of potential to get into bad situations and write some very confusing code.

**Comment by henryiii** [comment]
Agreed, it wouldn't be useful or helpful for us. We can list Lyra in our "other known parsers" section, though!

**Comment by jstaursky** [comment]
OK I see your points. Thanks

**Comment by henryiii** [comment]
If you want to keep the open till I add Lyra as a known alternative, that would be okay. ;)
