### ISSUE TITLE
integer flags not working with optional

### ISSUE THREAD

**Issue by wolfv** [henryiii/CLI11#731]
I think integer flags aren't working when wrapped in a `std::optional`. Not sure if that's a bug or not.

This works for additive flags (e.g. `-v -v -v`)

```
    int p = 0;
    app.add_flag("-p", p, "Parameter");
```

However, this can only count to `1`:

```
    std::optional<int> p = 0;
    app.add_flag("-p", p, "Parameter");
```

Any ideas on how to fix this?

**Comment by phlptp** [comment]
The fact that it worked before was a bit of glitch a recent change made it such that only integral types (`int`, `int64`, `uint32`, `uint64`,etc) will have this behavior as default.  
For other types this kind of behavior can be explicitly enabled by using `->multi_option_policy(CLI::MultiOptionPolicy::Sum);`  This policy change allows that kind of behavior to work for options as well,  previously control of this was somewhat hidden.  It allows it to be turned off for integer types if desired.
