### ISSUE TITLE
Subcommand callback unexpected executed twice with configurable(true)

### ISSUE THREAD

**Issue by turnef** [henryiii/CLI11#732]
I have just started using CLI11, so I apologize if I'm making a mistake or misunderstanding something fundamental.  When I add a subcommand to the parent application, set ```configurable(true)```, and register a callback on the subcommand instance, I find that triggering the subcommand from a configuration file results in the registered callback executing twice.  The code below demonstrates the issue:

```c++
#include <iostream>
#include "CLI/CLI11.hpp"

using namespace std;

int main(int argc, char** argv) {

   CLI::App app{"subcommands with callbacks from config files"};
   app.set_config("--config");

   CLI::App* subA = app.add_subcommand("a", "subcommand a");
   subA->configurable(true);
   subA->callback([](){ cout << "cmd_a callback" << endl;});

   CLI11_PARSE(app, argc, argv);
   return 0;
}
```
Compiling that and executing it like so:
```
% driver --config a.cfg
```
where the contents of a.cfg are simply:
```
[a]
```
results in the output:
```
cmd_a callback
cmd_a callback
```
However, if I just invoke it directly from the command line without the --config option, like so:
```
% driver a 
```
I get the output I would expect:
``` 
cmd_a callback
```
I stepped through the code in the debugger, and while I must admit I don't completely understand what's going on under the hood of CLI11, it looked to me like the callback was being triggered in the processing of the configuration file and then again when the parent application subcommands were being processed.  I wasn't sure what, if anything I was doing incorrectly; or if there may be a problem within CLI11 itself.  Any advice or suggestions you can offer would be greatly appreciated.  Thanks for your time.

**Comment by phlptp** [comment]
This probably a bug,  I don't know that this scenario was explicitly tested so a fix is probably needed.   We will get a patch in soon,
