### ISSUE TITLE
How to parse arguments after `--` ?

### ISSUE THREAD

**Issue by RayZ0rr** [henryiii/CLI11#744]
I am trying to create a program that take args like this (`find` and `ls` are the arguments here):
```
~$ multrun find ls
```
I would also like to run it as follows:
```
~$ multrun -- find ls
```
How should I go about achieving this?
I read the documentation a lot but I can't figure it out logically. I worked up a solution by trial and error but I don't feel right without knowing the logic behind it.

Resources used:
1) https://cliutils.github.io/CLI11/book/
2) https://github.com/CLIUtils/CLI11/blob/main/README.md

**Comment by phlptp** [comment]
"--" is a positional mark meaning anything that comes after that in the command line is considered a positional.  

so you would want some option 
```
std::vector<std::string> args;
app->add_option("args",args,"all arguments");
```
on parse if this was the only argument
then everything would end up in the args vector in both those cases.  
the reason for "--" is so you can support things like
```
~$ multrun -v -- find -v ls
```
or something like that  where the first -v is some modification to multrun and the second is an argument to find.  

there is also `positionals_at_end()` modifier to CLI which basically means that once CLI encounters a positional all the rest are positionals as well.

**Comment by RayZ0rr** [comment]
Thank you for the clarification. My solution was to use the following:
```
  CLI::Option *cmd_opt =
    app.add_option("cmd", "Commands to run");
  cmd_opt->required();
  cmd_opt->take_all();
  cmd_opt->allow_extra_args() ;
```
I hope this option makes sense. Also, :- 
1. Now, that I have `allow_extra_args` here, I don't need it in the main app?
2. Are the following same?
```
  cmd_opt->take_all();
  cmd_opt->allow_extra_args() ;
```
```
  cmd_opt->expected(0);
  cmd_opt->allow_extra_args() ;
```

**Comment by phlptp** [comment]
They are not exactly the same, but they would have the same effect, when run on an option with no arguments.

**Comment by phlptp** [comment]
when you set some of those on the main app it sets the default for all options,
