### ISSUE TITLE
Options are processed as the order specified in command line not as defined in souce code.

### ISSUE THREAD

**Issue by ilongshan** [henryiii/CLI11#763]
The following code snippet has two flag options. 
```
int main(int argc, char **argv) {
    CLI::App app{"Test"};
    app.add_flag_callback("-V", []() {
        printf("show version\n");
        exit(0);
    }, "show version");
    app.add_flag_callback("-L", []() {
        printf("show license\n");
        exit(0);
    }, "show license");
    CLI11_PARSE(app, argc, argv);
    exit(0);
}
```

```./a.out -L -V``` and ```./a.out -V -L``` all output "show version".
The options are processed as the order defined in source code. Does it support the order as specified in command line, ```./a.out -L -V``` will output "show license" and ```./a.out -V -L``` outputs "show version"?

**Comment by phlptp** [comment]
Options are generally assumed to be independent of eachother or the dependencies are defined in the definition so the processing is done by order of definition when done at the end.  It is possible to enable the `trigger_on_parse` for particular options.  This modifier will execute the callback when the option is parsed vs after all options are parsed. 

````c++
int main(int argc, char **argv) {
    CLI::App app{"Test"};
    app.add_flag_callback("-V", []() {
        printf("show version\n");
        exit(0);
    }, "show version")->trigger_on_parse();
    app.add_flag_callback("-L", []() {
        printf("show license\n");
        exit(0);
    }, "show license")->trigger_on_parse();
    CLI11_PARSE(app, argc, argv);
    exit(0);
}
```

**Comment by ilongshan** [comment]
It works. Thanks @phlptp
