### ISSUE TITLE
Customize the option placeholder in help message.

### ISSUE THREAD

**Issue by ilongshan** [henryiii/CLI11#764]
Here is a code snippet.
```
int main(int argc, char **argv) {
    CLI::App app{"Test"};
   int screen_width;
    m_app.add_option("-x", screen_width, "force displayed m_width");
    CLI11_PARSE(app, argc, argv);
    exit(0);
}
```
When running the above code with -h, the following will be outputed. We can see that option "-x" is followed with "INT", which is the type of "-x" option. But I cannot change the "INT" to something other message like "screen_width" as "-x screen_width".
```
Usage: Test [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  -x INT                      force displayed m_width
```

Hope there is a way to specify the placeholder.

**Comment by phlptp** [comment]
that "INT" or whatever you want instead of it can be specified by using the `type_name` modifier.  
```c++
m_app.add_option("-x", screen_width, "force displayed m_width")->type_name("screen_width");
```

**Comment by ilongshan** [comment]
It works. Thanks @phlptp
