### ISSUE TITLE
Does CLI11 support single dash with multiple chars, like "-fs"?

### ISSUE THREAD

**Issue by ilongshan** [henryiii/CLI11#765]
When running the following code with '-h' option, 
```
int main(int argc, char **argv) {
    CLI::App app{"Test"};
   bool is_full_screen;
    m_app.add_option("-fs", is_full_screen, "force full screen");
    CLI11_PARSE(app, argc, argv);
    exit(0);
}
```
it outputs errors:
```
libc++abi: terminating with uncaught exception of type CLI::BadNameString: Invalid one char name: -fs
```
Does CLI11 support single dash with multiple chars, like "-fs"?

**Comment by phlptp** [comment]
No, there is a purposeful choice in CLI11 to not support non-standard options such as that directly.  

See 
https://gitter.im/CLI11gitter/Lobby?at=62e1565b22c53438bcf57c53
for a similar discussion and some options you could use to handle this if it is really needed.

**Comment by ilongshan** [comment]
Thanks @phlptp , I will try it.

**Comment by phlptp** [comment]
Adding the Gitter discussion here for the record as Gitter seems to have changed links on us. 

Q. Hi, would it be at all possible to have a multi-char flag such as -module? Or is there maybe a workaround to do this?

A. This is explicitly disallowed in CLI11. The general way to workaround if you really non standard syntax is to specify allow extras, then either process the extra arguments which could include the non-standard flag after regular processing or in an app callback that grabs the remaining() arguments and processes them directly. There are also other tricks you can play with validators and validate_positionals if it was necessary to do some processing on the non standard options in the midst of processing.
