### ISSUE TITLE
Warning with -Wconversion: conversion to 'double' from 'int64_t'

### ISSUE THREAD

**Issue by zeroxia** [henryiii/CLI11#770]
gcc 7.5
linux ubuntu 18.04
Using single file version from this release:
https://github.com/CLIUtils/CLI11/releases/tag/v2.2.0

I got this warning:

`CLI11.hpp:2424:19: warning: conversion to ‘double’ from ‘int64_t {aka long int}’ may alter its value [-Wconversion]`

**Comment by phlptp** [comment]
This was resolved by #805 and adding -Wconversion flags to some of the builds in #813
