### ISSUE TITLE
Validators for container options?

### ISSUE THREAD

**Issue by garyo** [henryiii/CLI11#779]
If I have an option that's a vector of pairs and I'd like to validate the the first element of each pair is one of a set of strings, can that be done with a Validator? It seems like Validators all have to take a std::string rather than an arbitrary type.
For instance, how to validate this option?
```c++
  static std::vector<std::pair<std::string, std::string>> updates; // field should be "f1" or "f2", value can be any string
  opt = update->add_option("fields", updates, "Fields to update, as <field> <value> ...");
```

**Comment by phlptp** [comment]
Validators take a string, but you can use converters to check conversions.  
If you only want to validate 1 of the field of a pair you can use the `application_index(int)` property on a validator to specify and index of the argument to apply the validator to.  For example `application_index(0)` would only be applied to the first argument.
