### ISSUE TITLE
[Question] How can I know if the program is executed without parameters?

### ISSUE THREAD

**Issue by freitagfelipe** [henryiii/CLI11#818]
Hi, first of all thank you for taking your time to see my question! My doubt is if exists a way to know if the program is executed with nothing, like ```./app```, because I'd like to display the help command if that behavior is achieved.

**Comment by phlptp** [comment]
Setting up 
`app.require_option()`  will generate an error if no arguments are passed.  

if you wanted to have the behavior be expected but generate help what I would suggest is 

```C++
app.preparse_callback([](size_t argCount){
      if (argCount==0)
      {
           throw(CLI::CallForHelp);
      }
});
```

Then it should be just like `program --help`
