### ISSUE TITLE
Help messages of sibling subcommands

### ISSUE THREAD

**Issue by VolkerChristian** [henryiii/CLI11#819]
Hello all,

I am having troubles in getting the correct help messages depending on specified subcommands, especially if there a sibling subcommands.

Assume the following small example. 

```
CLI::App app("Some nice discription");

int x = 7;
app.add_option("-x", x, "An integer value");

std::string name;
app.add_option("-n,--name", name, "Some required string");

bool flag;
app.add_flag("-f,--flag", flag, "A flag option");

int y = 3;
CLI::App* sub1 = app.add_subcommand("sub1", "Subcommand 1");
sub1->add_option("--sub1_opt", y, "An integer value for sub1");

int z = 4;
CLI::App* sub2 = app.add_subcommand("sub2", "Subcommand 2");
sub2->add_option("--sub2_opt", z, "An integer value for sub2");

CLI11_PARSE(app, argc, argv);

return 0;
```

Here `sub1` and `sub2` are sibling subcommands.

If I run the application (assume the application is called `mainapp`) using
```
> mainapp --help
```
I get the expected output
```
Usage: mainapp [OPTIONS] [SUBCOMMAND]

Options:
  -h,--help                   Print this help message and exit
  -x INT                      An integer value
  -n,--name TEXT              Some required string
  -f,--flag                   A flag option

Subcommands:
  sub1                        Subcommand 1
  sub2                        Subcommand 2
```
If I run the application using
```
> mainapp sub1 --help
```
I will also get the expected output
```
Subcommand 1
Usage: mainapp sub1 [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --sub1_opt INT              An integer value for sub1

```
Using
```
> mainapp sub2 --help
```
gives me
```
Subcommand 2
Usage: mainapp sub2 [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --sub2_opt INT              An integer value for sub2
```
what is also expected.

**When now both sibling subcommands are specified like for instance**
```
> mainapp sub1 --sub1_opt 3 sub2 --help
```
I get the unexpected help message for subcommand `sub1` instead that for subcommand `sub2`:
```
Subcommand 1
Usage: mainapp sub1 [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --sub1_opt INT              An integer value for sub1

```
How can I achieve in that case to get the help message for subcommand `sub2`? 
For `mainapp sub1 --sub1_opt 3 sub2 --help` I would expect the output to be
```
Subcommand 2
Usage: mainapp sub1 --sub1_opt 3 sub2 [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --sub2_opt INT              An integer value for sub2

```

Thank you and best regards
Volker

**Comment by phlptp** [comment]
That could be changed in the code.   The current code when selecting a subcommand to process `help` for always selects the first subcommand used.    It could be changed to select the last one used.  Which would probably correct in a higher percentage of uses like you observed, but wouldn't be 100% accurate either for example  
```sh
mainapp sub1 --help sub2 --arg1
```

**Comment by VolkerChristian** [comment]
Thank you for the hint! I managed to change the behaviour by modifying `App::help(...)` a bit (quick hack).

```
CLI11_NODISCARD CLI11_INLINE std::string App::help(std::string prev, AppFormatMode mode) const {
    if(prev.empty())
        prev = get_name();
    else
        prev += " " + get_name();

    // Delegate to subcommand if needed
    auto selected_subcommands = get_subcommands();
    if(!selected_subcommands.empty()) {
//        return selected_subcommands.at(0)->help(prev, mode);
        return selected_subcommands.back()->help(prev, mode);
    }
    return formatter_->make_help(this, prev, mode);
}
```
Is there a way to find out the last given subcommand before the `--help` or `--help-all` flags, so that `mainapp sub1 --help sub2 --arg1` also behaves as expected?

**Comment by phlptp** [comment]
Your modification is what I was thinking of doing, so if you want to make a PR with that change I think we could incorporate it.  

As for getting it to work for the subcommand given immediately before.  I don't have a good solution.    Help processing is handled a little differently than other options so it goes first and bypasses some other checks.    So you could add "help" directly on the subcommand so it doesn't fallthrough to main help.      The other option at present would be to disable the built in option,  `.set_help_flag("")`  and create your own directly  
```C++
app.add_flag_callback("--help",[](){throw CLI::CallForHelp();},"call this help")->disable_flag_override()->trigger_on_parse();
```

this would trigger the help immediately when parsed and the last selected subcommand would always be the one help was called with as the others would not have even been processed yet.    This would also require your modification above.
