### ISSUE TITLE
Getting map-like data from config

### ISSUE THREAD

**Issue by siilky** [henryiii/CLI11#821]
I have a map-like structure in config

```
[map]
a = 1
b = 2
```

Is it possible to get its contents in some readable form?

I have added 
```
auto map = cfg.add_subcommand("map");
map->allow_config_extras();
```
but `remaining()` gives me only field names like `"a", "b"` without values. It appears also I cannot provide some 'global' subcommand callback for more options.

Interesting that at the same time when I provide `map.a=1 map.b=2` from command line, app's `remaining()` returns the full form like `"map.a=1"`

**Comment by phlptp** [comment]
This is likely an inconsistency in the way config files extras are handled.  I don't know of a good workaround at present, but this is probably symptomatic of a bug/oversight that should be fixed.
