### ISSUE TITLE
Include directories should be set to SYSTEM if not stand-alone

### ISSUE THREAD

**Issue by Krzmbrzl** [henryiii/CLI11#833]
If CLI11 is not built as a standalone library, but instead as part of another project (e.g. via submodule or via cmake's FetchContent) `target_include_directories` should make use of the `SYSTEM` option. This will have the effect that the compiler will not emit any warnings for these include files, even if included in files for which the warning settings would normally cause a warning to be emitted.

So as a trivial example, if in your header you somewhere had
```cpp
unsigned int i = -1;
```
and I compile my project with  `-Wsign-conversion`, I get a warning for this line in _your_ header, if I include that in _my_ source file (for which that warning applies). Marking the CLI11 headers as "system headers" will make the compiler silently ignore that warning - which seems to be what downstream users want...

**Comment by Krzmbrzl** [comment]
Note: If you agree that this is desirable, I could create a PR for this

**Comment by phlptp** [comment]
I think this would be of interest.
