### ISSUE TITLE
Validation for custom Range struct

### ISSUE THREAD

**Issue by dmf254** [henryiii/CLI11#834]
Hello, 

I'd like to parse an option with the format "--foo-range 50:100" into a custom Range struct. I'm able to use the lexical_cast overload to do this just fine, but I'd like to add additional validation for excluding negative numbers and possibly setting a min/max range. Is there a way I could use a CLI transformer to take the input and then use some validators on the low and high end values of the range? Hopefully the following code shows what I'm thinking.

```c++

struct Range {
    uint64_t low;
    uint64_t high;
};

// Naive...
bool is_negative(const std::string& input)
{
    return input[0] == '-';
}

namespace CLI::details {

template <> bool lexical_cast<Range>(const std::string &input, Range &output)
{
    auto split = utils::split_string(input, ':');

    // Validate the split size
    if (!std::cmp_equal(split.size(), 2)) {
        throw CLI::ValidationError("Could not split {} by :", input);
    }

    // Validate that the range contains positive numbers
    for (auto& str : split) {
        if (is_negative(str)) {
            throw ValidationError(fmt::format("A range cannot take a negative number: {}", str));
        }
    }

    // Possible min/max range validation here...

    output.low = std::stoull(split[0]);
    output.high = std::stoull(split[1]);
    return true;
}

template <> constexpr const char *type_name<Range>() { return "RANGE A:B"; }

}

int main(int argc, char** argv)
{
    Range range;

    CLI::App app;
    app.add_option("--foo-range", range, "Range for foo");
    app.parse("--foo-range 50:100");

    assert(range.low  == 50);
    assert(range.high == 100);
}
```

**Comment by phlptp** [comment]
One thing you could do is define range as std::pair<uint64_t,uint64_t>  

For example 
```C++
using Range =std::pair<uint64_t,uint64_t>;

int main(int argc, char** argv)
{
    Range range;

    CLI::App app;
    app.add_option("--foo-range", range, "Range for foo")->delimiter(":")->check(CLI::NonNegativeNumber)->type_name("RANGE A:B");

    app.parse("--foo-range 50:100");

    assert(range.low  == 50);
    assert(range.high == 100);
}
```
This should do everything in your test without needing the extra lexical cast overloads and would also support `--foo-range A B`  if that was desired.

**Comment by dmf254** [comment]
> One thing you could do is define range as std::pair<uint64_t,uint64_t>
> 
> For example
> 
> ```c++
> using Range =std::pair<uint64_t,uint64_t>;
> 
> int main(int argc, char** argv)
> {
>     Range range;
> 
>     CLI::App app;
>     app.add_option("--foo-range", range, "Range for foo")->delimiter(":")->check(CLI::NonNegativeNumber)->type_name("RANGE A:B");
> 
>     app.parse("--foo-range 50:100");
> 
>     assert(range.low  == 50);
>     assert(range.high == 100);
> }
> ```
> 
> This should do everything in your test without needing the extra lexical cast overloads and would also support `--foo-range A B` if that was desired.

This works great. Thank you for the help!
