### ISSUE TITLE
to_path() from README doesn't exist

### ISSUE THREAD

**Issue by asmaloney** [henryiii/CLI11#836]
In the [Note on using Unicode paths](https://github.com/CLIUtils/CLI11#note-on-using-unicode-paths) section of the README, it recommends using `CLI::to_path` to handle UTF-8 on Windows.

This function doesn't seem to exist in 2.3.2 (downloaded [CLI11.hpp](https://github.com/CLIUtils/CLI11/releases/download/v2.3.2/CLI11.hpp) from release page).

I don't see an equivalent function - is there one?

Thank you!

**Comment by henryiii** [comment]
Unicode was just added a few weeks ago and is still in development only, not in a final release yet. That section probably needs a development feature emoji.

Feel free to switch to the 2.3.2 tag and look at that README ;).

**Comment by asmaloney** [comment]
Ah! Mystery solved.

Thanks Henry!
