### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by soroshsabz** [henryiii/CLI11#847]
ITNOA

Hi,

As you can see you does not have standard license, and some terms of your license has some restrictions, so I request to change license to MIT, to wider application.

I have discussion with [BillyONeal](https://github.com/BillyONeal) in https://github.com/microsoft/vcpkg-tool/pull/864, and I suggest using CLI11 instead of writing another CLI from scratch, but the problem is license, so if you agree and change the license of the library, we can use this library in all MIT projects.

thanks to helping OSS!

**Comment by phlptp** [comment]
Every lawyer I have talked to on the subject has been of the opinion that the standard BSD 3-clause license and MIT licenses are equivalent and can be used freely in any project commercial or open source and used as components in projects licensed in other forms.    The only functional difference is that the standard BSD 3 clause includes a non endorsement clause which is entirely appropriate for any software written by a government or government funded entity.    All open source software we work on is BSD-3-clause if we want to it to be permissive.    

@henryiii  can speak to the original decision on licensing CLI11, but I don't see any reason to change the current license.  

BSD-3-clause is a pretty standard license there is nothing unusual about it and you are perfectly free to include any project using BSD-3-clause license in an MIT licensed project with no legal issues.    I have certainly seen it done many times.

**Comment by henryiii** [comment]
BSD 3-clause was specifically chosen to allow as many projects as possible to use CLI11 (the original license suggested to us was LGPL...). Unless there's a clear reason to change (and I'll have to contact lawyers back at UC if we wanted to start something like that), I think this is fine. We are already in use in various places, including in `microsoft/terminal`.

**Comment by soroshsabz** [comment]
Thanks for good description for me

:)
