### ISSUE TITLE
error: macro "CLI11_PARSE" requires 3 arguments, but only 1 given

### ISSUE THREAD

**Issue by evandrocoan** [henryiii/CLI11#854]
I am using v2.3.2 and I used the exemple on README.md:
![image](https://user-images.githubusercontent.com/5332158/224142600-15a08278-4105-4d9e-afb3-6651fbf92c91.png)

But it gives:
```
main.cpp:10:20: error: macro "CLI11_PARSE" requires 3 arguments, but only 1 given
   10 |     CLI11_PARSE(app);
```

Perhaps the example on README.md requires an update?

**Comment by henryiii** [comment]
That's the readme for `main`, not `v2.3.2`. Those are only in development. See also https://github.com/CLIUtils/CLI11/discussions/852.

**Comment by henryiii** [comment]
Also, due to https://github.com/CLIUtils/CLI11/issues/845, it's possible this interface will change. I'd use the previous README until a release has been made with Unicode support (and I'd also not use this API at all unless you need unicode).

**Comment by evandrocoan** [comment]
Thanks for answering. It would be nice if the main page were about the latest release. I as you may see, it is quite common to make this mistake.
