### ISSUE TITLE
error: 'argv' is not a member of 'CLI'

### ISSUE THREAD

**Issue by evandrocoan** [henryiii/CLI11#855]
I am using version v2.3.2 and trying this exemple on README.md:
![image](https://user-images.githubusercontent.com/5332158/224145503-e49d1488-03f7-482e-acdb-6367801d8977.png)

But looks like argc() is missing on namespace `CLI`:
```
main.cpp:10:40: error: 'argv' is not a member of 'CLI'
   10 |     CLI11_PARSE(app, CLI::argc(), CLI::argv());
```

**Comment by henryiii** [comment]
That's the readme for `main`, not `v2.3.2`. Those are only in development. See also https://github.com/CLIUtils/CLI11/discussions/852.
