### ISSUE TITLE
Allow resolution of escaped arguments.

### ISSUE THREAD

**Issue by ScottBailey** [henryiii/CLI11#871]
Given a program `exe` with the following help:

```
Usage: exe [OPTIONS] flags

Positionals:
  flags TEXT_REQUIRED         Compiler flags.

Options:
  -O       output name
```

The following command line, as expected, fails:
`exe -O2`

The following commands line, which should work, fails:
`exe \\-O2`

The end user could remove the escapes themselves; however, it seems appropriate for CLI11 to handle this.

**Comment by phlptp** [comment]
on the command line the `\` is probably acting as an escape sequence to the shell itself so probably getting passed as -O2 in both cases.    Which would get read as triggering the option and missing the required positional.  

Not sure you want CLI to be doing escape sequence interpretation on its own since often enough you want the fully escaped string to get passed into whatever program you are running.  CLI already has a positional marker `--` so you could do 
```sh
exe -- -O2
```

and that should drop the `-O2` into the positional

**Comment by ScottBailey** [comment]
> and that should drop the `-O2` into the positional

For a toy program that works, but imagine a more complicated program with multiple flags and positionals.

**Comment by ScottBailey** [comment]
Edited `exe \-O2` to `exe \\-O2`.

**Comment by phlptp** [comment]
For more complex programs what I usually do then is have an option for the positional and combined with validators on the positionals and validate_positionals modifier.  

``` C++
app.add_option("--flags,flags",flags,"flags")->validate_positionals()->required
```

then for complex sequences the positionals can be in different orders and a user can directly specify them if need be.

**Comment by phlptp** [comment]
As for the removal of the escape sequences, that should probably be done through Transforming Validators, rather than something that is built in.    Then it could be enabled as needed for specific options.

**Comment by ScottBailey** [comment]
Okay, I like that option. Let me do some testing and see if it fits my needs.

**Comment by ScottBailey** [comment]
So is there value to adding an Escape transformer or shall I just keep this in my own code?
```
class EscapeTransformer : public Validator {
```

**Comment by ScottBailey** [comment]
Is [this](https://github.com/CLIUtils/CLI11/compare/main...ScottBailey:CLI11:escape_transformer) worth a PR?

**Comment by phlptp** [comment]
@henryiii can comment further, but my inclination would be to wait.  There is some work ongoing about splitting apart the Validators file into the core part and an additional optional library.    Until the optional library is in place I would probably recommend not adding any more validators.     Once it is in then I think there would be an opening for additional validators to be added.

**Comment by ScottBailey** [comment]
For now, I think I'll just use a lamda for my transform. It's good enough for me. But I do feel like there should be a "built in" way to escape input.

**Comment by ScottBailey** [comment]
Using a lambda worked well enough; however, there is some value to allowing a much more functional escape transformer than I suggested.
