### ISSUE TITLE
Bind to non-string type variables is not working.

### ISSUE THREAD

**Issue by xrui94** [henryiii/CLI11#873]
I have two questions，and my dev environment：
OS：Windows 10
Compiler：VC2022
C++ std：C++17

1. Bind a value to some int type variables by app.add_option(), if I set the 4th args as "true", it can not be compiled successfully.
![image](https://user-images.githubusercontent.com/29156275/235150772-59b44a64-5bb0-477a-a90e-901ad1cc0381.png)

2. Bind a value to a not-string type variable, like int, float, double, my code is compiled successfully, but crash when running. 

![image](https://user-images.githubusercontent.com/29156275/235149586-d3cbb9fa-6fa1-4afe-b33c-eab032012f91.png)

**Comment by phlptp** [comment]
For #1. the fourth argument in that case was deprecated and removed several versions ago.  use `capture_default_str()` to achieve the same effect.  

For the second is it crashing on construction of the option?

**Comment by phlptp** [comment]
Ah I see what is going on.   line 55 and line 63 both have the same option `-n`  that will cause a runtime exception to be thrown.

**Comment by xrui94** [comment]
Yes, my first question, I understand it. The reason for the compilation failure is that I referenced an outdated blog and documention [https://cliutils.github.io/CLI11/book/chapters/options.html](https://cliutils.github.io/CLI11/book/chapters/options.html). 

 For the second issue, it did crash while constructing the option, the program print "a3", but did not print "a4".
![image](https://user-images.githubusercontent.com/29156275/235156139-ebcd33bb-eb60-4b9d-b7b9-e0d0fcbb9cb1.png)

**Comment by phlptp** [comment]
See the comment above,  it is generating a duplicate option exception as you have multiple `-n` as options

**Comment by xrui94** [comment]
> See the comment above, it is generating a duplicate option exception as you have multiple `-n` as options

Yes, the repeated - n caused the program to crash, but the 71 line code, bind "- h, -- height" to height var, will still crash. I have checked and confirmed that '- h, - height' is not duplicated.

![image](https://user-images.githubusercontent.com/29156275/235157993-658946ed-2f78-4338-b455-d1eb187be862.png)

I am so sorry, It's my problem.  “-h” bind to the "help" by default， so it is duplicated always. Thank you very much for helping me. Compared to gflags, cli11 is a particularly great project. I will close the issue.

**Comment by phlptp** [comment]
Just an FYI you can change the help flag
```cpp
app.set_help_flag("-?,--help");
```

to whatever you want

**Comment by xrui94** [comment]
> Just an FYI you can change the help flag
> 
> ```c++
> app.set_help_flag("-?,--help");
> ```
> 
> to whatever you want

Got it, thank you. Wishing you a happy life!
