### ISSUE TITLE
Unicode support: automatically widen on windows when option is assigned a std::filesystem::path

### ISSUE THREAD

**Issue by jmarrec** [henryiii/CLI11#875]
I've seen #804, and it does widen in check_path for the CLI:ExistingXXXX validator. https://github.com/CLIUtils/CLI11/pull/804/files#diff-212772a3245e02e1fb8bf60ed69b5c89eb1b4f109e459b3294ff1edbd6c6aa27R131

Assuming this MCVE

```c++
#include <CLI/CLI.hpp>
#include <fmt/format.h>
#include <fmt/std.h>     // Formatting std::filesystem::path

#include <filesystem>

namespace fs = std::filesystem;

int main(int argc, char** argv) {

  CLI::App app("test path");
  fs::path dir;
  app.add_option("DIR", dir, "Directory")->check(CLI::ExistingDirectory);

  CLI11_PARSE(app);

  fmt::print("{} - {}\n", dir, fs::exists(dir));
}
```

In the resulting executable directory:

```shell
mkdir voilà
./test voilà
```

Ideally that would work on both unix and windows.

On windows, the CLI:ExistingDirectory is perfectly fine since it does widden when checking, but the resulting `fs::path dir` doesn't exist and it prints `"tÃ©rmica" - false`

**Comment by jmarrec** [comment]
Note: the workaround is this

```c++
app.add_option_function<std::string>(
      "DIR", [&dir](const std::string& s) { dir = CLI::to_path(s); }, "Directory")
    ->check(CLI::ExistingDirectory);
```

**Comment by phlptp** [comment]
looks like we might have to double check the direct support for std::filesystem paths in a flag.

**Comment by jmarrec** [comment]
so, Template MetaProgramming (TMP) is not my strong suit, but I think I understand why this happens.

Turns out TypeTools does try to do it around here:

1.

https://github.com/CLIUtils/CLI11/blob/4a14b78ff44ee4e25105d0ec7d6fc1fbd7bbca5e/include/CLI/TypeTools.hpp#L1027-L1032

2.

 https://github.com/CLIUtils/CLI11/blob/4a14b78ff44ee4e25105d0ec7d6fc1fbd7bbca5e/include/CLI/TypeTools.hpp#L1043-L1050

The thing is, for std::filesystem::path, it's both string_assignable and wstring_assignable, on all platforms. But it resolves to object_category::string_assignable anyways.

https://gcc.godbolt.org/z/YWErffnjn

Since TMP isn't my forte, I'm not exactly sure how to fix it cleverly, but I can think of trying to reject the string version if `std::is_same<T, fs::path>::value_type`

**Comment by jmarrec** [comment]
@phlptp I had missed your PR #876 (unfortunately, given the time I spent doing so)  and opened #878.

The difference between my PR and yours is that I am not forcing `std::wstring` for all types but only select ones (`std::filesystem::path` only and **only on windows**  at the moment but it's extensible). 

This has the advantage of limiting side effects. Maybe that's warranted or not, but the things I question are:

* I'm not sure we want to prefer `std::wstring` on Unix for `std::filesystem::path `
* I'm not sure how many types in the stdlib are both constructible/assignable from std::string / std::wstring and whether prefering std::wstring makes sense there.

**Comment by jmarrec** [comment]
running your AppTest on Ubuntu: https://github.com/CLIUtils/CLI11/pull/876/files#diff-0ff7a70520a03cef17c26c405f4a189d134e19e89b2da40b848967d7f06c5a74R1718

```
/media/DataExt4/Software/Others/CLI11/tests/AppTest.cpp:1723: FAILED:
due to unexpected exception with message:
  filesystem error: Cannot convert character sequence: Invalid or incomplete
  multibyte or wide character
```

**Comment by phlptp** [comment]
I was debating that as well, whether to be specific for fs::path on windows or be more general.  I kind of came to the conclusion that wide strings are a potentially more general case and in situations where both are supported which appears to be somewhat rare, wide string support should be preferred.

**Comment by jmarrec** [comment]
I'm not an expert on the subject. I would expect this to work if that were true though, am I missing something?

https://gcc.godbolt.org/z/fzTojq6hW

```c++
int main() {
    std::string s("voilà.txt");
    fs::path p(s);
    fmt::print("{}\n", p.native());

    std::wstring ss(L"voil\u00E0.txt");
    // Both throw
    // terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
    // what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
    fs::path pw(CLI::widen(s));
    fs::path pw(ss);
}
```
