### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by patlecat** [henryiii/CLI11#884]
May I ask if you have a roadmap of what's to come for v2.4 and when?

**Comment by henryiii** [comment]
The biggest thing is reworking unicode before release. See https://github.com/CLIUtils/CLI11/issues/845.

**Comment by patlecat** [comment]
Sounds good, more Unicode support is always needed in C++! For when is the release of 4 planned?

**Comment by henryiii** [comment]
It's out!

**Comment by patlecat** [comment]
Thanks mate!
