### ISSUE TITLE
Incorrect/misleading error when flag and ->required() are combined

### ISSUE THREAD

**Issue by samipfjo** [henryiii/CLI11#885]
So I clearly wasn't firing on all cylinders when I wrote this, but I did the following:

```c++
add_option("-option", option, "flags are intrinsically optional")
    ->required();
```

Clearly dumb, yes, but a mistake that's easy to make. At present this case isn't handled, and leads to a `BadNameString::OneCharName` exception being thrown rather than something signaling the problem.

Given the ease of making this mistake, I believe it would be worthwhile to handle this case and provide an exception that points novice (or tired) programmers in the correct direction.

**Comment by phlptp** [comment]
Noted: thanks,  agree the error there can probably use a bit of clarity.
