### ISSUE TITLE
Configuration files not working with envname

### ISSUE THREAD

**Issue by r1viollet** [henryiii/CLI11#890]
# Description 

Configuration files are handled as an option, however the `envname` setting does not work with them.

```
  app.set_config("--config")->envname("MY_CONFIG_FILE");
```

# Additional information 

Indeed the order in which we consider options shows that we consider files before environment variables. Hence the environment variable can not be taken into account. 

# Possible workaround 

I made a workaround where I set default value of the config file, to the environment variable's value.

# Expected behaviour

Make it impossible to add an environment variable to prevent confusion, or read the environment variable when we create the option in the set_config flow.

**Comment by phlptp** [comment]
This seems like an oversight.  The prioritization for general options is correct that config files should come before environmental variables, but the config option is special so if no specific file is given then the environmental variable should    be checked which I don't believe is happening currently.    I will make a fix and check soon.
