### ISSUE TITLE
[Feature Request] Allow an option to be overridden by configuration

### ISSUE THREAD

**Issue by summerclock** [henryiii/CLI11#894]
When options are passed in both CLI and configuration, the parser seems to ignore the value in configuration, I looked through the relevant code, and only when the option is empty (not set), the configuration assignment is performed. 
Is it possible to allow one or all options to be overridden by something in the configuration? For example, add a flag similar to `overrideable` to `Option` or `App`. If it is set to true, the option value in the configuration will be given priority when parsing, followed by the option value passed on the command line.

**Comment by phlptp** [comment]
The priority of option values has always been command line>config file>environment values> default values.   On the rare occasions when that priority is not what you want.   I have processed the different parts in stages, collecting the config files, then processing them, then running again with the remaining command line.    Allowing the priority of processing to be changed in the program has the potential to cause a lot of user frustration if a parameter cannot be overridden with the command line line.

**Comment by summerclock** [comment]
You're right. In fact, I'm currently in a very atypical situation where the command-line options are fixed and cannot be changed. I can only influence the parameter parsing by modifying the source code or configuration files. 
Inspired by your advice, I have found a workaround that involves multiple passes of parsing, and it works fine, although not as elegantly. Given the rare use case I'm dealing with, it's acceptable. 

Thank you for your work.

**Comment by summerclock** [comment]
I'm closing this issue based on consensus reached above.
Thanks for your guidance.

**Comment by martin-braun** [comment]
@summerclock I'm currently looking to do the same. I want to read an argument `--data-dir` and load a configuration within such dir, but I want to be able to override `data-dir` in the configuration for further usage of other things, giving the user the opportunity to specify a `data-dir` that will redirect to a different `data-dir`.

Mind sharing an example with me, please?

**Comment by summerclock** [comment]
> @summerclock I'm currently looking to do the same. I want to read an argument `--data-dir` and load a configuration within such dir, but I want to be able to override `data-dir` in the configuration for further usage of other things, giving the user the opportunity to specify a `data-dir` that will redirect to a different `data-dir`.
> 
> Mind sharing an example with me, please?

Hi Martin, here is my initial solution.

``` cpp
  // ...
  app.set_config("--config_file", "/path/to/config.ini", "Config file");
  // ...
  
  CLI11_PARSE(app, argc, argv);
  fs::path config_file = app.get_config_ptr()->as<std::string>();
  std::ifstream ifs(config_file);
  if (ifs)
  {
    // 1. clear all options, parse only configs and get pointer to options in config file
    app.clear();
    app.parse_from_stream(ifs);
    std::vector<Option *> configs = app.get_options([](const CLI::Option* opt) { return !opt->empty(); });
    // 2. re-parse all options, and now we can clear only config options since we've got pointers to them)
    app.parse(argc, argv);
    for (auto& config : configs)
    {
      std::cout << "config: " << config->get_name() << std::endl;
      config->clear();
    }
    // 3. parse only config file, since we've cleared config options, parser will not be affected by command line priority
    ifs.clear();
    ifs.seekg(0);
    app.parse_from_stream(ifs);
    ifs.close();
  }
```

In short, you just need to make sure that the options you are interested in have not been set before parsing the configuration file. You can achieve this by obtaining the pointer and clearing it.

If you have any other ideas, feel free to share them!

**Comment by martin-braun** [comment]
@summerclock Thank you, but I came to the realization that adding the options before setting the configuration works fine, I had some issues somewhere else. It seems to update my `--data-dir` after reading the configuration so the desired outcome is absolutely possible.

All I do is:

```cpp
    command_line_options options{};
    CLI::App cli{"My Server"};
    cli.formatter(std::make_shared<WrapFormatter>());
    options.data_dir = "path/to/default/data-dir";
    cli.add_option("--data-dir", options.data_dir, "Path in which to store persistent data")
            ->type_name("DIR")
            ->capture_default_str();
    cli.set_config(
               "--config-file",
               (options.data_dir / "server.conf").u8string(),
               "Path to config file specifying additional command-line options")
            ->capture_default_str();
    // more options down the line
```
