### ISSUE TITLE
Range Example

### ISSUE THREAD

**Issue by singularian** [henryiii/CLI11#906]
Is it possible to include a integer range vector example in CLI11?

A command would take range vectors and expand them into integer vectors.
input   1 2 3 4-8 10-12
output 1 2 3 4 5 6 7 8 10 11 12

**Comment by singularian** [comment]
cmd --range 1-5 7 11 12 13 20-22
1 2 3 4 5 11 12 13 20 21 22

**Comment by phlptp** [comment]
There is nothing built in to generate range information.  My recommendation would be to create a custom callback for the option and do the conversion yourself.    We might consider a custom separator/expansion operation at some point in the future, but it is not there at present and wouldn't anticipate that kind of thing being available in the near future.  So a custom callback on the option is probably going to be your best path to supporting something like this.

**Comment by singularian** [comment]
I created a call back.
It is also a useful example for the CLI11.

#include "../external/CLI11.hpp"
#include <iostream>
#include <map>
#include <string>
#include <regex>

std::vector<std::string> split(std::string &s, char delim);

// ./testrange --range=1 1-3 12 19 22 22-23
int main(int argc, char **argv) {
    CLI::App app;

    std::vector<int> flvals;
    std::vector<std::string> v;
    app.add_option("--range", [&flvals, &v](std::vector<std::string> val){
    	// std::cout << "This option was given " << val.size() << " times." << std::endl;
	// std::cout << "Val " << val[0] << std::endl;
	char delim = '-';
	for(int i = 0; i<val.size(); i++) {
		if (std::regex_match (val[i], std::regex("([0-9]+)") )) { // 1
			flvals.push_back(std::stoi(val[i]));
		} else if (std::regex_match (val[i], std::regex("([0-9]+\\-[0-9]+)") ))	{ // 1-9 or 10-23
			std::string number = val[i];
			v = split(number, delim);
			if (v.size() == 2) {
				int a = std::stoi(v[0]);
				int b = std::stoi(v[1]);
				// the range should be 2-20 or the first number less than the second
				if (a < b) {
					for (int j = a; j <= b; j++) flvals.push_back(j);
				} else {
					return false;
				}
			}
		} else {
			return false;
		}

	}
    	return true;
    }, "Test Range")->expected(1,100)->allow_extra_args(true);
 

    CLI11_PARSE(app, argc, argv);

    for (int j = 0; j < flvals.size(); j++) {
	std::cout << flvals[j] << " ";
    }
    std::cout << std::endl;

    return 0;
}

std::vector<std::string> split(std::string &s, char delim) {
	std::stringstream ss(s);
	std::string item;
	std::vector<std::string> elems;
	while (std::getline(ss, item, delim)) {
		elems.push_back(item);
		// elems.push_back(std::move(item)); // if C++11 (based on comment from @mchiasson)
	}

	return elems;
}
