### ISSUE TITLE
How to automatically print help information without using the -h or --help flag?

### ISSUE THREAD

**Issue by qqwangxiaow** [henryiii/CLI11#909]
as the title suggests

**Comment by jzakrzewski** [comment]
Not sure if this is what you're asking, but `CLI::App` has a `help` method that you can call to get the help string.

**Comment by qqwangxiaow** [comment]
> Not sure if this is what you're asking, but `CLI::App` has a `help` method that you can call to get the help string.

thanks for you answer, I found a method.
app->failure_message(CLI::FailureMessage::help);
