### ISSUE TITLE
When will a new release contain Unicode?

### ISSUE THREAD

**Issue by HerrNamenlos123** [henryiii/CLI11#919]
Hi, thank you all for this amazing library. My library, too, follows utf8everywhere and UTF-8 support is essential for me.
I almost wanted to create Issues/PRs to that topic, but I realized it is already implemented in master.
However, I can only refer to GH Releases by their tag since I have to download the source archive in a script and I cannot use an arbitrary commit. Thus I am still bound to the old version from Jan 4 that does not support UTF-8 correctly.

Sorry if it seems like I'm rushing, but I have no idea about internal development of this library or any roadmaps. When is the next release scheduled? Otherwise, would it be a problem to simply create a minor release pointing to the latest commit?

Thank you all for considering it!

**Comment by henryiii** [comment]
We need to rework the unicode handling, which is why we haven't released yet, actually. The current system relies on non-standard access of args; I'd prefer to stick with standards since it has caused some small issues. Tracking issue is https://github.com/CLIUtils/CLI11/issues/845.

**Comment by henryiii** [comment]
It's out!
