### ISSUE TITLE
Memory leak when disabling help

### ISSUE THREAD

**Issue by dgregorius** [henryiii/CLI11#924]
You only erase the command from the list, but don't delete it

**Comment by phlptp** [comment]
The underlying option structure is wrapped in a unique_ptr, and the corresponding element of the vector is erased when the help is disabled same as removing any other option.  So the unique_ptr destructor takes care of the actual free operation.

 As best as I can tell there is no memory leaks in that process.  Can you be more specific on your concern?

**Comment by dgregorius** [comment]
This is what I added:

	void disable_help() {
		for (auto command = _commands.begin(); command != _commands.end(); ++command) {
			if ((*command)->name == "h" && (*command)->alternative == "--help") {
				**delete  *command;**
				_commands.erase(command);
				break;
			}
		}
	}

**Comment by dgregorius** [comment]
Actually never mind. It seems Google took me to the wrong project.
