### ISSUE TITLE
How to pass option value starting with dash?

### ISSUE THREAD

**Issue by ApsarasX** [henryiii/CLI11#931]
I built a WebAssembly (wasm) virtual machine and developed its command line interface (CLI) using CLI11 library. The CLI is named wasmcli. However, I faced issues while trying to pass certain option values prefixed with '-' to the '--args' option of wasmcli.

My code is as follows:

```cpp
// ...
CLI::App CLIParser;
std::vector<std::string> Args;
CLIParser.add_option("--args", Args, "Entry function args");
CLI11_PARSE(CLIParser, argc, argv);
// ....
```

For example, I used emscripten to compile bzip2 into bzip2.wasm, and used wasmcli to run this bzip2.wasm.

For bzip2, you can execute `bzip2 -k -f -z bzip2_testfile` to compress the test file.

So I execute `wasmcli bzip2.wasm --args "-k" "-f" "-z" "bzip2_testfile"`, but got 
```
The following argument was not expected: bzip2_testfile
Run with --help for more information.
```

Then I attempted to use its equivalent command and, to my surprise, it worked unexpectedly.
`wasmcli bzip2.wasm --dir . --args "-k" --args "-z" --args "-f" --args "bzip2_testfile"`

If I want `wasmcli bzip2.wasm --args "-k" "-f" "-z" "bzip2_testfile"` to work properly, how should I modify it?

**Comment by phlptp** [comment]
Do you want everything that comes after "--args" to fall into the Args vector?  

if you were to add 
```C++
CLIParser.add_option("--args", Args, "Entry function args")->delimiter(' ');
```

then 

`wasmcli bzip2.wasm --dir . --args "-k -z -f bzip2_testfile"`  
would work,  which is how I, most often, have these things work

**Comment by henryiii** [comment]
FYI, subcommands have a feature specifically for this, `.prefix_command()`.

**Comment by phlptp** [comment]
going to close this as the example has been added.
