### ISSUE TITLE
How to hide display of specific flags

### ISSUE THREAD

**Issue by JulianKnodt** [henryiii/CLI11#933]
If I have a command:
`app.add_option("--example1,--example2", ...)`, but I only want to display  `--example1` in the help message, is there a way to do that?

I realize I could do two `add_option`s, but I feel like there should be an easier way

**Comment by phlptp** [comment]
The way it was designed was that all option strings given in a single add option are treated equivalently.  
If you want one of them to be treated differently in any way, then the way to do that is make two options like you suggest that modify the same variable or have the same callback.  with one of them given the `->group("")` modifier to hide it.

**Comment by JulianKnodt** [comment]
Cheers, thank you!
