### ISSUE TITLE
Issue with add_subcommand(std::shared_ptr>) overload

### ISSUE THREAD

**Issue by James-02** [henryiii/CLI11#934]
The following C++20 code (Compiled with gcc11), using the latest CLI11 release, adds two subcommands to a main `CLI::App_p`

The `add_subcommand(std::shared_ptr)` overload does not work as expected (unless I am confused about the usage).
I expected this to act in the same manor as the `add_subcommand(std::string)` overload, as shown below.

```C++
#include <CLI/CLI.hpp>

int main(int argc, char** argv) {
    // initialise a shared pointer of the main app object
    auto app = std::make_shared<CLI::App>("main");
    
    // initialise subcommand with shared pointer
    app->add_subcommand(std::make_shared<CLI::App>("sub-1"));

    // initialise a subcommand by string
    app->add_subcommand("sub-2");

    CLI11_PARSE(*app, argc, argv)
    return 0;
}
```

The subcommand that was added as a shared_pointer (CLI::App_p) is not parseable and is shown under the help command as being a part of the Option group: Subcommands, instead of the actual subcommands.

```
$ cli --help
main
Usage: cli [OPTIONS] [SUBCOMMAND]

Options:
  -h,--help                   Print this help message and exit
[Option Group: Subcommands]
  sub-1

Subcommands:
  sub-2                       
```

Upon attempting to parse the subcommands `sub-2` parses correctly, however with `sub-1` I receive the following error:
```
$ cli sub-1
The following argument was not expected: sub-1
```

My main goal is to be able to exclusively use shared pointers (`CLI::App_p`) of subcommands in my program instead of raw pointers (`CLI::App*`)

**Comment by phlptp** [comment]
Try this
```C++
#include <CLI/CLI.hpp>

int main(int argc, char** argv) {
    // initialise a shared pointer of the main app object
    auto app = std::make_shared<CLI::App>("main");
    
    // initialise subcommand with shared pointer
    app->add_subcommand(std::make_shared<CLI::App>("description of sub 1","sub-1"));

    // initialise a subcommand by string
    app->add_subcommand("sub-2");

    CLI11_PARSE(*app, argc, argv)
    return 0;
}
```

the first argument to the constructor for an app is the the description, the second optional one is a key name.  
you an also use `->alias` to add other names that will trigger like a subcommand

**Comment by phlptp** [comment]
option groups are subcommands without a name, which is why it showed up as an option group in your original code.

**Comment by James-02** [comment]
Ah okay, thank you 👍
