### ISSUE TITLE
add_option() not assigning when the subcommand is declared directly from a CLI::App

### ISSUE THREAD

**Issue by steyou** [henryiii/CLI11#940]
In my code, I have adapted the [nested example](https://github.com/CLIUtils/CLI11/blob/main/examples/nested.cpp) so that a single subcommand is used to derive what following arguments are available and how the program is executed (minimal reproducible example):

```C++
int main(int argc, char* argv[]) {
    CLI::App app("Program Selector: Choose from two programs.");
    app.require_subcommand(1);

    CLI::App *apple_program = app.add_subcommand("apple", "Compute an apple.");
    int apple_amount{10};
    apple_program->add_option("amount", apple_amount, "Number of apples to compute.");
    apple_program->callback([&](){
        std::cout<<std::to_string(apple_amount)<<"\n";
        //Compute the apples
    });

    CLI::App *orange_program = app.add_subcommand("orange", "Compute an orange.");
    bool orange_delicious{false};
    std::string orange_filepath;
    orange_program->add_option("--delicious", orange_delicious, "Are the oranges delicious?");
    orange_program->add_option("-f, --filepath", orange_filepath, "Where the oranges are located on the filesystem.");
    orange_program->callback([&](){
        std::cout<<std::to_string(orange_delicious)<<"\n";
        std::cout<<orange_filepath<<"\n";
        //Compute the oranges
    });

    CLI11_PARSE(app, argc, argv);

    return 0;
}
```

The logical difference between this example and the original is that I don't need deeper subcommands thus I instead apply `add_option()` directly to the `apple_program` or `orange_program`, etc. I want something like:

```
$ ./fruity apple 10
$ ./fruity orange --delicious "here"
$ ./fruity orange "/over/there"
```

...and so on.

The issue I am having is that with my modifications, the variables aren't being assigned and stay as their initial values. If I run the above, I get the following outputs:

```
$ ./fruity apple 50
10 (expected 50)

$ ./fruity orange --delicious -f here
0 (expected 1)
(expected "here")
```

Is this a bug with CLI11 or a mistake on my part? It is unusual since I intuited my changes only from the examples in the documentation.

Thanks

**Comment by steyou** [comment]
What's more is that if I set `required()` on an option using this approach, I get this strange error:
```
$ ./fruity apple 50
amount is required
Run with --help for more information.
```
but 50 is the `amount`!

**Comment by phlptp** [comment]
I copied your main to a test executable.  
```sh
./tester apple 50
50
```

```sh
./tester orange --delicious 1 -f here
1
here
```

if I add the required flag to the "amount" option everything behaves as I expected.  
what version are you running, and what compiler?

**Comment by steyou** [comment]
Oops. It was an unrelated mistake. I was executing the binary through a bash script which doesn't interpret/ pass my arguments correctly.
