### ISSUE TITLE
How to create an argument that consumes all subsequent args?

### ISSUE THREAD

**Issue by abrownsword** [henryiii/CLI11#942]
I need to have an argument that consumes the remainder of the command line.  I'm using `allow_extra_args` however, it doesn't seem to consume anything starting with a double dash?  The desired behaviour is similar to `--` but I need it to be after a named arg of my choosing.

**Comment by phlptp** [comment]
the `prefix_command()` modifier for subcommands is for that purpose.

**Comment by abrownsword** [comment]
Sorry if it should be obvious, but I do not understand how to use `prefix_command()` to achieve my objective here.  I don't want to start capturing the remaining args "on the first unrecognized item", instead I want to start capturing the remaining args immediately after a specific arg (i.e. `--args <extras>`).  The `--` mechanism seems to do what I want, but I want it to have an explicit name after the dashes.

**Comment by phlptp** [comment]
If you want an argument form that ignores all subsequent values then the prefix_command is the right approach.  

```C++
#include <CLI/CLI.hpp>
#include <iostream>
#include <string>

int main(int argc, const char *argv[]) {

    int value{0};
    CLI::App app{"Test App"};
    app.add_option("-v", value, "value");

    auto *subcom = app.add_subcommand("sub", "")->prefix_command();
    subcom->alias("--sub");
    CLI11_PARSE(app, argc, argv);

    std::cout<<"value ="<<value<<std::endl;
    std::cout<<"after Args:";
    for (const auto& aarg : subcom->remaining())
    {
        std::cout<<aarg<<" ";
    }
    std::cout<<std::endl;
}
```
This program will print out everything after the "sub" or "--sub"
```sh
> tester -v 27 --sub -v 34 --nine jin eight
value =27
after Args:-v 34 --nine jin eight
```

**Comment by phlptp** [comment]
the key is a subcommand with nothing in it, and if you want a different form use the alias modifier.  Then all the subsequent arguments will be accessible in the `remaining()`
This answer is also relevant to #931

**Comment by abrownsword** [comment]
Works like a charm, thank you.  I just couldn't see how the various pieces needed to fit together.
