### ISSUE TITLE
Feature missing

### ISSUE THREAD

**Issue by rafiw** [henryiii/CLI11#943]
Hey,
I used your great library (again) and I was missing an option but I'm not sure how common it is, an option to check that few arguments have the same size.
something like
```
CLI::App app("test");
std::vector<std::string> arg1;
std::vector<std::string> arg2;
auto opt = app.add_option("--arg1", arg1, "t1")->delimiter(',');
app.add_option("--arg2", arg2, "t2")->delimiter(',')->same_size(opt);
```
do you think it's a good addition?
I can quickly add and send a PR if you want.
Thanks

**Comment by phlptp** [comment]
I don't think it is common enough to warrant a specific modifier for that kind of check.    There would also  be a lot of ambiguities to resolve with the expected counts and multi argument processing.   

The typical way I have dealt with checks like what you are talking about that require checking multiple options simultaneously is through a callback on the app.

``` C++
CLI::App app("test");
std::vector<std::string> arg1;
std::vector<std::string> arg2;
auto opt = app.add_option("--arg1", arg1, "t1")->delimiter(',');
app.add_option("--arg2", arg2, "t2")->delimiter(',');
app.final_callback([&arg1,&arg2](){
                     if (arg1.size()!=arg2.size()){
                          throw CLI::ValidationError("arg1 and arg2 must be the same size");
                     }
 });

```

or you could do the callback before the option callbacks are called and just get the count directly from the options passed into the callback.
