### ISSUE TITLE
Cannot get options as vector

### ISSUE THREAD

**Issue by Sil3ntStorm** [henryiii/CLI11#954]
By default it appears it is **not possible** to get a vector of strings out of an option.

```
int main(int argc, char** argv) {
    CLI::App app;
    std::vector<std::string> def_value{"0.0.0.0", "::"};
    app.add_option("--ip")->expected(0, 100)->default_val(def_value);

    app.parse(argc, argv);
    auto value = app.get_option("--ip")->as<std::vector<std::string>>();
    return value.size() == 2 ? 0 : 1;
}
```

value will be a vector of strings with size 1, which the first element being `[0.0.0.0,::]` rather than the expected vector of string with size 2 with the elements being `0.0.0.0` and `::`.

This is due to there being a check on `allow_extra_args_` bool before even attempting to parse the internal representation of a vector in `_add_result` [Option_inl.hpp:634](https://github.com/CLIUtils/CLI11/blob/main/include/CLI/impl/Option_inl.hpp#L634)

**Comment by phlptp** [comment]
try
```C++
int main(int argc, char** argv) {
    CLI::App app;
    std::vector<std::string> def_value{"0.0.0.0", "::"};
    app.add_option("--ip")->expected(0, 100)->default_val(def_value)->delimiter(',');

    app.parse(argc, argv);
    auto value = app.get_option("--ip")->as<std::vector<std::string>>();
    return value.size() == 2 ? 0 : 1;
}
```

default_val is stored as a single string,  without the delimiter specified it doesn't know how to separate them again and would assume you just wanted the single string representing the value.
