### ISSUE TITLE
can not parse Chinese character

### ISSUE THREAD

**Issue by how2051** [henryiii/CLI11#955]
`->check(CLI::ExistingFile)` option can not parse Chinese character

if I input a Chinese file name, it tell me `File does not exist`
if I rename it into a English name, it works fine

e.g.  If i go `./myprogram --input 文件名.txt` it failed, but if I go `./myprogram --input filename.txt` it works fine

**Comment by tansy** [comment]
I don't think it has anything to do with parser, nor even your program, but everything with your console/terminal.
Just tested your name and it works in my console. So I suspect the problem is in encoding that your console or terminal is using. The name is Unicode, on this website it's UTF-8, but what is your console program using?

**Comment by henryiii** [comment]
Are you using the dev version of cli11 and Unicode support?

**Comment by how2051** [comment]
I use `git bash` and `power shell` and it all failed to find the file
![图片](https://github.com/CLIUtils/CLI11/assets/55384174/c246fe6d-c37a-49c8-8d0a-7b8611047bcb)
![图片](https://github.com/CLIUtils/CLI11/assets/55384174/3c458a08-dcc9-4d17-8080-8d457f6a3493)

how can I check if it is, like u said, a encoding problem ?



> I don't think it has anything to do with parser, nor even your program, but everything with your console/terminal. Just tested your name and it works in my console. So I suspect the problem is in encoding that your console or terminal is using. The name is Unicode, on this website it's UTF-8, but what is your console program using?

**Comment by how2051** [comment]
nah I use the release version

> Are you using the dev version of cli11 and Unicode support?

**Comment by tansy** [comment]
Can other programs read this file?
You use powershell, which I don't know, and, in the same time \`ls', which is *nix command, so I don't know.
Maybe `type 文件名.txt`, or `type "文件名.txt"`, although me think that \`type\` is cmd command, not powershell. Try to read it with any other program. If it reads it then it's problem with your program, it'd not them with a console/terminal.

How about asking internet "[how to change encoding in power shell](https://duckduckgo.com/?q=how+to+change+encoding+in+power+shell&t=ffab&ia=web&iax=qa)"?

I found some:
[about_Character_Encoding](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_character_encoding)
[powershell-utf-8-encoding-chcp-65001](https://www.delftstack.com/howto/powershell/powershell-utf-8-encoding-chcp-65001/)
[how-to-configure-the-encoding-for-powershell-console](https://stackoverflow.com/questions/35573209/how-to-configure-the-encoding-for-powershell-console)
[utf-8-output-from-powershell](https://stackoverflow.com/questions/22349139/utf-8-output-from-powershell) (althought this is about output)

It seems to be windows/powershell question.

**Comment by henryiii** [comment]
I think you need unicode handling, which isn't out yet, but will be in 2.4 (and is in main branch).

**Comment by henryiii** [comment]
2.4 is out with Unicode handling!
