### ISSUE TITLE
Can I chain input strings with && ?

### ISSUE THREAD

**Issue by ari26squared** [henryiii/CLI11#956]
Basically, are their characters that would terminate parsing and then start parsing again ?

if load and draw are sub-commands

load && draw

would execute both as if it were passed

load
draw

**Comment by phlptp** [comment]
In many cases 
```sh
exec load draw
```
will work fine,  it will call the first subcommand then the second.   There are some cases where this is potentially ambiguous, there is a subcommand terminator "++" that should work. 

```sh
exec load ++ draw
```

in general you can call subcommand multiple time or multiple subcommands

**Comment by ari26squared** [comment]
interesting.

i just tried it again (after finally understanding positional option)

so i have a sub-command `player` that i added an `add` sub-command to
in that add sub-command i added a positional argument (instead of using allow extras before i knew what a positional argument is !)

i have a sub-command `draw` at the same level as `player`, but the following does not work

```
player add luz ++ draw
The following argument was not expected: draw
Run with --help for more information.
```

**Comment by phlptp** [comment]
can you add the `fallthrough()` modifier on the add sub-sub-command   or at the app level, and see if that changes things

**Comment by ari26squared** [comment]
i have narrowed it down to `require_subcommand(1)`

**Comment by ari26squared** [comment]
on the base app

**Comment by ari26squared** [comment]
oh, so the subcommands fail after detecting more than 1 subcommand because they inherit from the base app ??

**Comment by phlptp** [comment]
if you had `require_subcommand(1)` on the base_app then once you call the first one, it won't even check if command is a valid subcommand after that.  So in your example if player and draw are both children of the base app.  Then `require_subcommand(1)`on the base app would prevent draw from executing.   I would probably do `require_subcommand(1,0)` if you want to require at least 1, but allow more.

**Comment by ari26squared** [comment]
Thanks ! That solved the issue.
