### ISSUE TITLE
[Question] `--help` as a potential remaining arg: only enable if no other arguments is passed

### ISSUE THREAD

**Issue by jmarrec** [henryiii/CLI11#961]
I've got a bit of a pickle. Basically I've got a subcommand that potentially executes a ruby/python script file, and I want to be able to pass remaining arguments as argc/argv to that file. I've worked around it and it runs nicely, and here is a MCVE: https://github.com/jmarrec/OSCLI11/blob/2aac569b7949508fadc66c62e90937bfc1dffbae/src/main.cpp#L48-L58

```c++
  {
    auto* execute_ruby_scriptCommand = experimentalApp->add_subcommand("execute_ruby_script", "Executes a ruby file");
    fs::path rubyScriptPath;
    execute_ruby_scriptCommand->add_option("path", rubyScriptPath, "Path to ruby file")->required(true)->check(CLI::ExistingFile);
    execute_ruby_scriptCommand->allow_extras(true);
    execute_ruby_scriptCommand->footer("Any additional arguments passed after the ruby file are forwarded");
    execute_ruby_scriptCommand->callback([&] {
      fmt::print("rubyScriptPath={}\n", rubyScriptPath);
      fmt::print("remaining()={}\n", execute_ruby_scriptCommand->remaining());
     // In reality I passthrough the remaining args here
    });
  }
```

I've noticed a corner case, where basically `execute_ruby_script myfile.rb --help` triggers CLI11's help, instead of forwarding it to the script file to display its own help. I can completely disable the help_flag and that works, but I'd like actually to have a situation where the built-in help is displayed only if no other args to the subcommand are passed:

* `program subcommand --help`  => Displays help
* `program subcommand path.rb --help` => Forward `--help` to the script (treat as remaining)

Can you think of a way to do this please?

----

I've tried preparse_callback chekcing for arity, but can't seem to figure out how to test if the args are the `path`, `--help` or anything else

**Comment by jmarrec** [comment]
The only way I can think of, which I find smelly, is this:

```c++
    std::vector<std::string> args(argv, std::next(argv, static_cast<std::ptrdiff_t>(argc)));
    execute_ruby_scriptCommand->set_help_flag();  // Remove the help flag
    execute_ruby_scriptCommand->preparse_callback([&](std::size_t arity) {
      if (arity == 1 && args.back() == "--help") {
        throw CLI::CallForHelp();
      }
    });
```

**Comment by phlptp** [comment]
```C++
 {
    auto* execute_ruby_scriptCommand = experimentalApp->add_subcommand("execute_ruby_script", "Executes a ruby file");
    fs::path rubyScriptPath; //NOTE this will cause a seg fault when run due the variable going out of scope
   std::vector<std::string> args;  //NOTE this will cause a seg fault when run due the variable going out of scope
    execute_ruby_scriptCommand->add_option("path", rubyScriptPath, "Path to ruby file")->required(true)->check(CLI::ExistingFile);
    execute_ruby_scriptCommand->add_option('args",args,"arguments for the ruby script);
    execute_ruby_scriptCommand->positionals_at_end(true);
    execute_ruby_scriptCommand->footer("Any additional arguments passed after the ruby file are forwarded");
    execute_ruby_scriptCommand->callback([&] {
      fmt::print("rubyScriptPath={}\n", rubyScriptPath);
      fmt::print("remaining()={}\n", args);
     // In reality I passthrough the remaining args here
    });
  }
```

What you probably want to do is capture the remaining arguments in a vector and use that instead of the remaining functionality.     Just note that as the capture variables need to defined outside of the scope  otherwise they will go out of scope during execution and cause a seg fault.

**Comment by jmarrec** [comment]
That is much better thank you!
