### ISSUE TITLE
Help on help, by example

### ISSUE THREAD

**Issue by tansy** [henryiii/CLI11#973]
Little request to make example about help/usage function.
I tried to use automatic help but it doesn't show all options in help . In fact it doestn't show any options added by \`add_option()' at all.
Would you mind to make an example how to use this feature.
It would also be beneficial if you added example how to overload usage message.

```C++
#include "CLI11.hpp"

int main(int argc, char** argv)
{
    std::string input_file_name, output_file_name;
    int level, subopt;

    CLI::App app{ "cl11 help" };
    app.require_subcommand(1);
    CLI::App* const encode = app.add_subcommand("e", "encode")->ignore_case();
    encode->add_option("input", input_file_name, "input file")->option_text(" ")->required()->check(CLI::ExistingFile);
    encode->add_option("output", output_file_name, "output file")->option_text(" ")->required();
    encode->add_option("-l, --level", level, "encoding level")->option_text("(1..9")->check(CLI::Range(1, 9))->default_val(5);
    encode->add_option("-r, --remove", level, "remove input file");
    encode->add_flag  ("-s, --suboption", subopt, "suboption")->option_text(" ");

    CLI::App* const decode = app.add_subcommand("d", "decode")->ignore_case();
    decode->add_option("input", input_file_name, "input file")->option_text(" ")->required()->check(CLI::ExistingFile);
    decode->add_option("output", output_file_name, "output file")->option_text(" ")->required();

    encode->add_option("-H, --help-long", level, "show long help");

    CLI11_PARSE(app, argc, argv);

    return 0;
}
```

```
$ ./cl11-help -h
cl11 help
Usage: cli11-help [OPTIONS] SUBCOMMAND

Options:
  -h,--help                   Print this help message and exit

Subcommands:
  e                           encode
  d                           decode
```

**Comment by phlptp** [comment]
help usually only shows the next level of options.  In your case all the options are in subcommands.   So 
```sh
cl11 e help
```
should show the options in the encode subcommand. 

There is a help_all flag that can be set which will show all options for all subcommands
```
set_help_all_flag(...)
```

**Comment by tansy** [comment]
I meant help, that shows all options, and their description, onev that most programs show with \`--help\` command line option.

If that is not possible, then how can one overload message printed by \`-h, --help\`?

**Comment by phlptp** [comment]
So the help flag option gets created by default.   This by default shows the help for all options directly of the app itself and its subcommands.   

What it sound like what you want is the default to be the help all in which case what you want is.  

```c++
#include "CLI11.hpp"

int main(int argc, char** argv)
{
    std::string input_file_name, output_file_name;
    int level, subopt;

    CLI::App app{ "cl11 help" };
   app.set_help_flag("");  //this will clear the existing help
   app.set_help_all_flag("-h,--help","Print this help message and exit");  //this will set the help all flag for the typical flags
    app.require_subcommand(1);
    CLI::App* const encode = app.add_subcommand("e", "encode")->ignore_case();
    encode->add_option("input", input_file_name, "input file")->option_text(" ")->required()->check(CLI::ExistingFile);
    encode->add_option("output", output_file_name, "output file")->option_text(" ")->required();
    encode->add_option("-l, --level", level, "encoding level")->option_text("(1..9")->check(CLI::Range(1, 9))->default_val(5);
    encode->add_option("-r, --remove", level, "remove input file");
    encode->add_flag  ("-s, --suboption", subopt, "suboption")->option_text(" ");

    CLI::App* const decode = app.add_subcommand("d", "decode")->ignore_case();
    decode->add_option("input", input_file_name, "input file")->option_text(" ")->required()->check(CLI::ExistingFile);
    decode->add_option("output", output_file_name, "output file")->option_text(" ")->required();

    encode->add_option("-H, --help-long", level, "show long help");

    CLI11_PARSE(app, argc, argv);

    return 0;
}
```

clearing the existing flag, and then using the help_all flag will use that as the default help which should do what you want.

**Comment by phlptp** [comment]
the `encode->add_option("-H, --help-long", level, "show long help");`  can probably be removed as that option will inherit to the subcommands

**Comment by tansy** [comment]
Thanks for the clarification as I was getting 'CLI:Option Asked Added'.
Tried
```
   app.set_help_flag("");
   app.set_help_all_flag("-h,--help","Print this help message and exit");
```
and it works now better.
Thank you.

PS.
Last thing - how to formally change usage message (\`Usage: prog [OPTIONS] SUB COMMAND\`)?
Have tied \`app.usage\` as I found it in Readme now but it's doesn't work, it's a sub command thing if I understand correctly.

**Comment by phlptp** [comment]
usage can take a string or string generation function.   And you can set it on the app and/or the individual subcommands

**Comment by tansy** [comment]
Ok, found it. I had old (released) header and it wasn't there.

```
CLI::App app;
(...)
app.usage("Usage: prog <command> [options] <arguments>");
```

Funny thing is the help message for help option looks like this:
```
Options:
  -h,--help...................
```
Dots represent empty spaces.


--
Thanks for the answers, shall I close it?

**Comment by phlptp** [comment]
If you have any suggestions on how to make the docs clearer that would be helpful, otherwise close it if you are satisfied

**Comment by tansy** [comment]
Maybe this example can be put in \`examples\'.
I have it slightly modified, can add some comments and put here or in PR.
