### ISSUE TITLE
Validation across multiple options

### ISSUE THREAD

**Issue by cconverse711** [henryiii/CLI11#976]
Is there any way to perform validation across multiple options, as in ensuring that none of them are in conflict? 

The particular scenario I have in mind is taking in two options where their values cannot match Think like ports for transmission and receiving: `--tx` and `--rx`; if given the same value, validation should fail. I've tried using a Validator with a lambda that captures both values and compares them, but it doesn't work quite right. Thanks in advance

**Comment by phlptp** [comment]
There are a couple ways this has been done in the past.  
1).   the app callback can check this and throw a `CLI::ValidationError` with the appropriate message
2).  a custom validator that either has memory to capture the values, or a lambda with which has ability to query the second option.  

1).  Has been my preferred method for multi option validation,  Usually just have the app or subcommand variable as a lambda capture in the callback, and we can do a coordinated check on all the values.

**Comment by cconverse711** [comment]
Thank you, that does the trick
