### ISSUE TITLE
can't handle last positional string argument if the previous positional argument is an array of strings

### ISSUE THREAD

**Issue by rpolasek-sde** [henryiii/CLI11#982]
if i have 2 required positional arguments:
- the 1st one `arg1` is `std::vector<std::string>`
- the 2nd one `arg2` is `std::string`

then the 2nd one is always ignored because all the positional arguments are consumed by the vector so it always fails with "`arg2` _is required_" error message.

example:

```
#include <iostream>
#include <string>
#include <vector>

#include <CLI/CLI.hpp>

int main(int argc, char* argv[]) {
    CLI::App app("cli11 - an example of positional arguments");

    std::vector<std::string> arg1;
    auto opt_arg1 = app.add_option("arg1", arg1, "array of argument #1");
    opt_arg1->required(true);

    std::string arg2;
    auto opt_arg2 = app.add_option("arg2", arg2, "argument #2");
    opt_arg2->required(true);

    std::string comment;
    app.add_option("--comment,-c", comment, "global comment");

    CLI11_PARSE(app, argc, argv);
    std::cout << app.config_to_str(true, false) << "\n\n";

    return 0;
}
```

```
./cli_positional_args --help
cli11 - an example of positional arguments
Usage: ./cli_positional_args [OPTIONS] arg1... arg2

Positionals:
  arg1 TEXT ... REQUIRED      array of argument #1
  arg2 TEXT REQUIRED          argument #2

Options:
  -h,--help                   Print this help message and exit
  -c,--comment TEXT           global comment
```
```
./cli_positional_args text1 text2 1
arg2 is required
Run with --help for more information.
```

**Comment by rpolasek-sde** [comment]
well, is that a solution? https://github.com/CLIUtils/CLI11/issues/295

**Comment by phlptp** [comment]
I think `positionals_at_end()` modifier on the app does what you want. 

Other solutions are if they have different properties, `validate_positionals()` is an option where it will only assign the positional if it passes validation.     Or just having them all as one vector and extracting the the last element after the parsing.  

But this situation is what `positionals_at_end()` is designed to handle.

**Comment by rpolasek-sde** [comment]
thank you for your confirmation.

**Comment by rpolasek-sde** [comment]
positionals_at_end() has solved the problem.
